### ISSUE TITLE
执行推理命令报错：ImportError: /root/miniconda3/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

### ISSUE THREAD

**Issue by yue001** [fishaudio/fish-speech#103]
执行 HTTP API 推理 和 WebUI 推理 都报错，信息如下：
环境：
Ubuntu22.04
Python  3.10 PyTorch  2.1.0
GPU ：NVIDIA GeForce RTX 2080 Ti, 1
torch Version: 2.3.0.dev20240229+cu121
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

命令：
`#python -m zibai tools.api_server:app --listen 127.0.0.1:6009`

输出：
```
2024-03-01 17:06:06,928 INFO Listening on 127.0.0.1:6009
2024-03-01 17:06:06,928 WARNING gevent not found, using threading instead
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.10/site-packages/zibai/__main__.py", line 5, in <module>
    main(parse_args(sys.argv[1:]))
  File "/root/miniconda3/lib/python3.10/site-packages/zibai/cli.py", line 348, in main
    application = options.get_application()
  File "/root/miniconda3/lib/python3.10/site-packages/zibai/cli.py", line 93, in get_application
    app = import_from_string(self.app)
  File "/root/miniconda3/lib/python3.10/site-packages/zibai/cli.py", line 133, in import_from_string
    return reduce(getattr, attrs_str.split("."), importlib.import_module(module_str))
  File "/root/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/buen/fish-speech/tools/api_server.py", line 32, in <module>
    import tools.llama.generate
  File "/root/buen/fish-speech/tools/llama/generate.py", line 28, in <module>
    from fish_speech.models.text2semantic.llama import Transformer
  File "/root/buen/fish-speech/fish_speech/models/text2semantic/__init__.py", line 1, in <module>
    from .lit_module import TextToSemantic
  File "/root/buen/fish-speech/fish_speech/models/text2semantic/lit_module.py", line 12, in <module>
    from fish_speech.models.text2semantic.llama import Transformer
  File "/root/buen/fish-speech/fish_speech/models/text2semantic/llama.py", line 12, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/root/miniconda3/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/root/miniconda3/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /root/miniconda3/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```

**Comment by Stardust-minus** [comment]
See #84

**Comment by AnyaCoder** [comment]
And #86

**Comment by yue001** [comment]
> See #84

It seems that the issue #84 has not been resolved, similar to what I encountered.

**Comment by yue001** [comment]
> And #86 Update (torch >= 2.2 automatically support flash-attn-2, but for some specific operators): ![image](https://private-user-images.githubusercontent.com/122108331/309440035-f45220c5-c71f-4325-a5f8-439669c5072d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTk3NzYsIm5iZiI6MTcwOTUxOTQ3NiwicGF0aCI6Ii8xMjIxMDgzMzEvMzA5NDQwMDM1LWY0NTIyMGM1LWM3MWYtNDMyNS1hNWY4LTQzOTY2OWM1MDcyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwMjMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmM4YTZmMjk2ZTg3ZDE4NjJiNGU0ZjU2NzkwNzgxMmFjN2JlOTQ3NzA1ZmNiZTVjNDI3M2RmMTkwM2Y4MDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wlGXnDr80pe58NCQcBDVD2wWeeXuWQl8tkXp2LALUEQ)

My torch version is 2.3, maybe I can try downgrading, and what versions of torchvision and torchaudio are appropriate for this?

**Comment by AnyaCoder** [comment]
> > And #86 Update (torch >= 2.2 automatically support flash-attn-2, but for some specific operators): ![image](https://private-user-images.githubusercontent.com/122108331/309440035-f45220c5-c71f-4325-a5f8-439669c5072d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTk3NzYsIm5iZiI6MTcwOTUxOTQ3NiwicGF0aCI6Ii8xMjIxMDgzMzEvMzA5NDQwMDM1LWY0NTIyMGM1LWM3MWYtNDMyNS1hNWY4LTQzOTY2OWM1MDcyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwMjMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmM4YTZmMjk2ZTg3ZDE4NjJiNGU0ZjU2NzkwNzgxMmFjN2JlOTQ3NzA1ZmNiZTVjNDI3M2RmMTkwM2Y4MDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wlGXnDr80pe58NCQcBDVD2wWeeXuWQl8tkXp2LALUEQ)
> 
> My torch version is 2.3, maybe I can try downgrading, and what versions of torchvision and torchaudio are appropriate for this?

You can try for the following:
<img width="271" alt="image" src="https://github.com/fishaudio/fish-speech/assets/122108331/64ea2cdf-27e5-4448-976f-b93e08bcf13b">
then locally install `flash-attn-2-2.5.2 python3.10 abi=False.whl`

**Comment by leng-yue** [comment]
We removed the deps of flash-attn in the dev branch, since newest PyTorch already come with that.
