### ISSUE TITLE
[BUG]OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like fishaudio/speech-lm-v1 is not the path to a directory containing a file named config.json.

### ISSUE THREAD

**Issue by Edisonwei54** [fishaudio/fish-speech#121]
**Describe the bug**
A config.json file was missing when loading the model.

**To Reproduce**
CUDA_VISIBLE_DEVICES=0,1 python tools/llama/generate.py \
    --text "要转换的文本" \
    --prompt-text "你的参考文本" \
    --checkpoint-path "checkpoints/text2semantic-400m-v0.2-4k.pth" \
    --num-samples 2 \
    --compile \
    --half

**Additional context**
When the program found that the file was missing, it tried to download it from the hugging face and timed out due to an incorrect download address

**Comment by Edisonwei54** [comment]
@leng-yue 我看见https://huggingface.co/fishaudio/speech-lm-v1/tree/main上面也没有喔，怎么办

**Comment by leng-yue** [comment]
你用的是什么版本? Huggingface 只有个 tokenizer, 所以没有 config.json 是正常的. 方便发下完整的报错堆栈么.

**Comment by Edisonwei54** [comment]
> 你用的是什么版本? Huggingface 只有个 tokenizer, 所以没有 config.json 是正常的. 方便发下完整的报错堆栈么.
2024-04-07 09:30:11.746 | INFO     | __main__:main:417 - Loading model ...
2024-04-07 09:30:14.715 | INFO     | __main__:load_model:359 - Restored model from checkpoint
2024-04-07 09:30:14.727 | INFO     | __main__:main:423 - Time to load model: 2.98 seconds
Traceback (most recent call last):
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f6555083190>, 'Connection to huggingface.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /fishaudio/speech-lm-v1/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6555083190>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
    response = _request_wrapper(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 392, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 68, in send
    return super().send(request, *args, **kwargs)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /fishaudio/speech-lm-v1/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6555083190>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: f9c165ca-7b95-403d-b472-dfcac2cccbe1)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1406, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lafei/edison/fish-speech/tools/llama/generate.py", line 495, in <module>
    main()
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lafei/edison/fish-speech/tools/llama/generate.py", line 425, in main
    tokenizer = AutoTokenizer.from_pretrained(tokenizer)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 794, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1138, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
  File "/opt/conda/envs/fish-speech/lib/python3.10/site-packages/transformers/utils/hub.py", line 441, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like fishaudio/speech-lm-v1 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by Edisonwei54** [comment]
> 你用的是什么版本? Huggingface 只有个 tokenizer, 所以没有 config.json 是正常的. 方便发下完整的报错堆栈么.

最新的...

**Comment by leng-yue** [comment]
挂个梯子吧, 你这还是 ConnectTimeoutError

**Comment by Edisonwei54** [comment]
> 挂个梯子吧, 你这还是 ConnectTimeoutError

我觉得我已经解决了这个问题，因为tokenizer参数的默认值不是我的正确路径，我指定为服务器上的tokenizer的目录就可以运行了
