### ISSUE TITLE
pip3 install -e .报错

### ISSUE THREAD

**Issue by xxxsjan** [fishaudio/fish-speech#124]
### 环境：
win10 + miniconda 

### 具体如下：
```
(fish-speech) PS D:\hello-word\front-end\GPT-SoVITS\fish-speech> pip3 install -e .
Obtaining file:///D:/hello-word/front-end/GPT-SoVITS/fish-speech
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting transformers>=4.35.2 (from fish-speech==0.1.0)
  Using cached transformers-4.39.3-py3-none-any.whl.metadata (134 kB)
Collecting datasets>=2.14.5 (from fish-speech==0.1.0)
  Using cached datasets-2.18.0-py3-none-any.whl.metadata (20 kB)
Collecting lightning>=2.1.0 (from fish-speech==0.1.0)
  Using cached lightning-2.2.2-py3-none-any.whl.metadata (53 kB)
Collecting hydra-core>=1.3.2 (from fish-speech==0.1.0)
  Using cached hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting tensorboard>=2.14.1 (from fish-speech==0.1.0)
  Using cached tensorboard-2.16.2-py3-none-any.whl.metadata (1.6 kB)
Collecting natsort>=8.4.0 (from fish-speech==0.1.0)
  Using cached natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Collecting einops>=0.7.0 (from fish-speech==0.1.0)
  Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
Collecting librosa>=0.10.1 (from fish-speech==0.1.0)
  Using cached librosa-0.10.1-py3-none-any.whl.metadata (8.3 kB)
Collecting vector-quantize-pytorch>=1.10.0 (from fish-speech==0.1.0)
  Using cached vector_quantize_pytorch-1.14.6-py3-none-any.whl.metadata (716 bytes)
Collecting rich>=13.5.3 (from fish-speech==0.1.0)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting gradio>=4.0.0 (from fish-speech==0.1.0)
  Using cached gradio-4.26.0-py3-none-any.whl.metadata (15 kB)
Collecting pypinyin>=0.49.0 (from fish-speech==0.1.0)
  Using cached pypinyin-0.51.0-py2.py3-none-any.whl.metadata (12 kB)
Collecting jieba>=0.42.1 (from fish-speech==0.1.0)
  Using cached jieba-0.42.1.tar.gz (19.2 MB)
  Preparing metadata (setup.py) ... done
Collecting g2p-en>=2.1.0 (from fish-speech==0.1.0)
  Using cached g2p_en-2.1.0-py3-none-any.whl.metadata (4.5 kB)
Collecting pyopenjtalk>=0.3.2 (from fish-speech==0.1.0)
  Using cached pyopenjtalk-0.3.3.tar.gz (1.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
     
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
     
     
      CMake Error at CMakeLists.txt:17 (project):
        Running
     
         'nmake' '-?'
     
        failed with:
     
         no such file or directory
     
     
      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      CMake is in the system path. Version:               cmake version 3.29.2
     
      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      Traceback (most recent call last):
        File "C:\miniconda3\envs\fish-speech\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\miniconda3\envs\fish-speech\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main   
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\miniconda3\envs\fish-speech\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\xpj\AppData\Local\Temp\pip-build-env-rtlb4iqz\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\xpj\AppData\Local\Temp\pip-build-env-rtlb4iqz\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\xpj\AppData\Local\Temp\pip-build-env-rtlb4iqz\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 191, in <module>
        File "C:\miniconda3\envs\fish-speech\lib\subprocess.py", line 457, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(fish-speech) PS D:\hello-word\front-end\GPT-SoVITS\fish-speech> 
```

好像是版本问题，有大佬会解决吗

**Comment by leng-yue** [comment]
你试下单独装这个包会不会报错?

**Comment by leng-yue** [comment]
最新版本删除了 flash attn 依赖

**Comment by XianYue0125** [comment]
我最近刚尝试成功pip install flash-attn 

参考教程https://github.com/Dao-AILab/flash-attention/issues/1469

从
https://github.com/kingbri1/flash-attention/releases
下载了对应的编译好的whl文件，然后直接pip install 这个whl

我是使用
pip install flash_attn-2.7.1.post1+cu124torch2.4.0cxx11abiFALSE-cp39-cp39-win_amd64

成功安装
