### ISSUE TITLE
[BUG]推理的时候报错

### ISSUE THREAD

**Issue by kingslyChen** [fishaudio/fish-speech#194]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.

**Additional context**
下载整合包训练完之后推理报错，错误如下：
Traceback (most recent call last):
  File "D:\ai\fish-speech-main-9051777030\fishenv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "D:\ai\fish-speech-main-9051777030\fishenv\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\ai\fish-speech-main-9051777030\fishenv\lib\site-packages\gradio\blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\ai\fish-speech-main-9051777030\fishenv\lib\site-packages\gradio\blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\ai\fish-speech-main-9051777030\fishenv\lib\site-packages\gradio\blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (inference_wrapper) didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [<gradio.components.audio.Audio object at 0x000001CEE608B3D0>, <gradio.components.audio.Audio object at 0x000001CEE613BDF0>, <gradio.components.audio.Audio object at 0x000001CEE613A680>, <gradio.components.audio.Audio object at 0x000001CEE613B010>, <gradio.components.html.HTML object at 0x000001CEE6138550>]
Received outputs:
    [None, <gradio.components.audio.Audio object at 0x000001CEE5E71060>, <gradio.components.audio.Audio object at 0x000001CE1954A620>, None]

**Comment by leng-yue** [comment]
该问题与 #200 一起讨论.
