### ISSUE TITLE
ValueError: Invalid model size [BUG]

### ISSUE THREAD

**Issue by henji-henji** [fishaudio/fish-speech#231]
**Describe the bug**
推理配置页面选择 LLAMA 模型会报错，不过似乎也只有在选择自己微调后的模型时会这样，选择没有微调的模型则不会。
之前的版本并不会这样，是近期才出现的问题。
The inferencing configuration page throws an error when selecting the LLAMA model. However, this seems to only happen when you choose your own fine-tuned model, not when selecting a model that has not been fine-tuned.
This was not an issue in previous versions and only appeared recently.

**To Reproduce**
Windows 10，最新拉取的代码
推理配置 - LLAMA 模型路径 - 选择自己微调后的模型 - LLAMA 模型配置部分显示“错误”

**Screenshots / log**
![image](https://github.com/fishaudio/fish-speech/assets/84775360/98fca769-8902-41ed-a181-bdd0b958a7c3)

> Traceback (most recent call last):
  File "D:\anaconda\fish-speech\lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "D:\anaconda\fish-speech\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\anaconda\fish-speech\lib\site-packages\gradio\blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "D:\anaconda\fish-speech\lib\site-packages\gradio\blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\anaconda\fish-speech\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\anaconda\fish-speech\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\anaconda\fish-speech\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\anaconda\fish-speech\lib\site-packages\gradio\utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "D:\Amazing\AUDIO\fish-speech\fish_speech\webui\manage.py", line 152, in change_llama_config
    raise ValueError("Invalid model size")
ValueError: Invalid model size

**Comment by AnyaCoder** [comment]
这个是一个比较破坏式的更新，不好意思（），你可以在这个模型的名字里面加上`large`或`medium`标识它是一个多大的模型

**Comment by henji-henji** [comment]
原来如此，感谢答复
