### ISSUE TITLE
torch\distributed\utils.py RuntimeError: Invalid scalar type

### ISSUE THREAD

**Issue by Hardwell99** [fishaudio/fish-speech#257]
There was no problem with the VQGAN and VITS training steps, but the following error occurred during the LLAMA training step. Does anyone know why and How to deal with it?

`2024-05-31 00:37:35.538 | INFO     | __main__:main:165 - Finished writing 1 shards to data\quantized-dataset-ft
2024-05-31 00:37:36.448 | INFO     | __main__:train_process:653 - text2semantic_medium_20240531_002158
2024-05-31 00:37:36.448 | INFO     | __main__:train_process:676 - ['python', 'fish_speech/train.py', '--config-name', 'text2semantic_finetune', 'project=text2semantic_medium_20240531_002158', 'ckpt_path=checkpoints/text2semantic-sft-medium-v1.1-4k.pth', 'trainer.strategy.process_group_backend=gloo', 'model@model.model=dual_ar_2_codebook_medium', 'tokenizer.pretrained_model_name_or_path=checkpoints', "train_dataset.proto_files=['data/quantized-dataset-ft']", "val_dataset.proto_files=['data/quantized-dataset-ft']", 'model.optimizer.lr=1e-5', 'trainer.max_steps=1000', 'data.num_workers=1', 'data.batch_size=6', 'max_length=2048', 'trainer.precision=32', 'trainer.val_check_interval=100', 'trainer.accumulate_grad_batches=1', 'train_dataset.use_speaker=0.5']
[2024-05-31 00:37:44,341][__main__][INFO] - [rank: 0] Instantiating datamodule <fish_speech.datasets.text.TextDataModule>
[2024-05-31 00:37:44,871][datasets][INFO] - PyTorch version 2.1.0+cu121 available.
[2024-05-31 00:37:44,877][datasets][INFO] - TensorFlow version 2.12.0 available.
[2024-05-31 00:37:45,224][__main__][INFO] - [rank: 0] Instantiating model <fish_speech.models.text2semantic.TextToSemantic>
[2024-05-31 00:37:47,138][__main__][INFO] - [rank: 0] Instantiating callbacks...
[2024-05-31 00:37:47,138][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2024-05-31 00:37:47,141][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.ModelSummary>
[2024-05-31 00:37:47,142][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.LearningRateMonitor>
[2024-05-31 00:37:47,142][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating callback <fish_speech.callbacks.GradNormMonitor>
[2024-05-31 00:37:47,144][__main__][INFO] - [rank: 0] Instantiating loggers...
[2024-05-31 00:37:47,145][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2024-05-31 00:37:47,160][__main__][INFO] - [rank: 0] Instantiating trainer <lightning.pytorch.trainer.Trainer>
Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.model_summary.ModelSummary'>]. Skipping setting a default `ModelSummary` callback.
GPU available: True (cuda), used: True
[2024-05-31 00:37:48,312][__main__][INFO] - [rank: 0] Logging hyperparameters!
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-05-31 00:37:51,998][__main__][INFO] - [rank: 0] Starting training!
[2024-05-31 00:37:52,001][__main__][INFO] - [rank: 0] Resuming from checkpoint: checkpoints/text2semantic-sft-medium-v1.1-4k.pth
[2024-05-31 00:37:52,002][__main__][INFO] - [rank: 0] Resuming weights only!
[2024-05-31 00:37:52,856][__main__][INFO] - [rank: 0] Error loading state dict: <All keys matched successfully>
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W socket.cpp:663] [c10d] The client socket has failed to connect to [LAPTOP-J7AMI8R3]:6711 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[2024-05-31 00:37:55,362][fish_speech.utils.utils][ERROR] - [rank: 0] 
Traceback (most recent call last):
  File "N:\Project\HuggingFace\fish-speech-main-20240525\fish-speech\fish_speech\utils\utils.py", line 66, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "N:\Project\HuggingFace\fish-speech-main-20240525\fish-speech\fish_speech\train.py", line 108, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\strategies\launchers\subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 963, in _run
    self.strategy.setup(self)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\strategies\ddp.py", line 171, in setup
    self.configure_ddp()
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\strategies\ddp.py", line 283, in configure_ddp
    self.model = self._setup_model(self.model)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\strategies\ddp.py", line 195, in _setup_model
    return DistributedDataParallel(module=model, device_ids=device_ids, **self._ddp_kwargs)
  File "D:\Software\Python3-10\Lib\site-packages\torch\nn\parallel\distributed.py", line 797, in __init__
    _sync_module_states(
  File "D:\Software\Python3-10\Lib\site-packages\torch\distributed\utils.py", line 292, in _sync_module_states
    _sync_params_and_buffers(process_group, module_states, broadcast_bucket_size, src)
  File "D:\Software\Python3-10\Lib\site-packages\torch\distributed\utils.py", line 306, in _sync_params_and_buffers
    dist._broadcast_coalesced(
RuntimeError: Invalid scalar type
[2024-05-31 00:37:55,366][fish_speech.utils.utils][INFO] - [rank: 0] Output dir: results/text2semantic_medium_20240531_002158
Error executing job with overrides: ['project=text2semantic_medium_20240531_002158', 'ckpt_path=checkpoints/text2semantic-sft-medium-v1.1-4k.pth', 'trainer.strategy.process_group_backend=gloo', 'model@model.model=dual_ar_2_codebook_medium', 'tokenizer.pretrained_model_name_or_path=checkpoints', "train_dataset.proto_files=['data/quantized-dataset-ft']", "val_dataset.proto_files=['data/quantized-dataset-ft']", 'model.optimizer.lr=1e-5', 'trainer.max_steps=1000', 'data.num_workers=1', 'data.batch_size=6', 'max_length=2048', 'trainer.precision=32', 'trainer.val_check_interval=100', 'trainer.accumulate_grad_batches=1', 'train_dataset.use_speaker=0.5']
Traceback (most recent call last):
  File "N:\Project\HuggingFace\fish-speech-main-20240525\fish-speech\fish_speech\train.py", line 135, in main
    train(cfg)
  File "N:\Project\HuggingFace\fish-speech-main-20240525\fish-speech\fish_speech\utils\utils.py", line 77, in wrap
    raise ex
  File "N:\Project\HuggingFace\fish-speech-main-20240525\fish-speech\fish_speech\utils\utils.py", line 66, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "N:\Project\HuggingFace\fish-speech-main-20240525\fish-speech\fish_speech\train.py", line 108, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\strategies\launchers\subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 963, in _run
    self.strategy.setup(self)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\strategies\ddp.py", line 171, in setup
    self.configure_ddp()
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\strategies\ddp.py", line 283, in configure_ddp
    self.model = self._setup_model(self.model)
  File "D:\Software\Python3-10\Lib\site-packages\lightning\pytorch\strategies\ddp.py", line 195, in _setup_model
    return DistributedDataParallel(module=model, device_ids=device_ids, **self._ddp_kwargs)
  File "D:\Software\Python3-10\Lib\site-packages\torch\nn\parallel\distributed.py", line 797, in __init__
    _sync_module_states(
  File "D:\Software\Python3-10\Lib\site-packages\torch\distributed\utils.py", line 292, in _sync_module_states
    _sync_params_and_buffers(process_group, module_states, broadcast_bucket_size, src)
  File "D:\Software\Python3-10\Lib\site-packages\torch\distributed\utils.py", line 306, in _sync_params_and_buffers
    dist._broadcast_coalesced(
RuntimeError: Invalid scalar type

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

**Comment by Hardwell99** [comment]
works on Win10 and environment are all meet pyobject.yoml

**Comment by AnyaCoder** [comment]
Perhaps you should use the fishenv environment and install the environment via `install_env.bat`.

**Comment by Hardwell99** [comment]
Running with the  provided bat command instead of trying to open it in PyCharm
