### ISSUE TITLE
llama微调data/protos is not a file or directory

### ISSUE THREAD

**Issue by wanglongpeng1** [fishaudio/fish-speech#261]
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/anaconda3/envs/fish_speed_t/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/anaconda3/envs/fish_speed_t/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/datahdd/wyz/wlp/fish-speech_5.30/fish_speech/datasets/text.py", line 260, in __iter__
    yield self.augment()
  File "/datahdd/wyz/wlp/fish-speech_5.30/fish_speech/datasets/text.py", line 302, in augment
    response = self.sample_data()
  File "/datahdd/wyz/wlp/fish-speech_5.30/fish_speech/datasets/text.py", line 274, in sample_data
    self.init_mock_data_server()
  File "/datahdd/wyz/wlp/fish-speech_5.30/fish_speech/datasets/text.py", line 234, in init_mock_data_server
    raise ValueError(f"{i} is not a file or directory")
ValueError: data/protos is not a file or directory
llama微调时第四步开始训练 报错                查了文档没找到这个文件应该在什么时候创建

**Comment by wanglongpeng1** [comment]
补充一下，这个需要的文件是第三步微调时生成的文件吗？

**Comment by 1nlplearner** [comment]
> 补充一下，这个需要的文件是第三步微调时生成的文件吗？

是的，改成对应目录就可以了
