### ISSUE TITLE
[BUG]使用 vits默认配置训练，解析不到指定地址的类 fish_speech.models.vits_decoder.modules.models.SynthesizerTrn

### ISSUE THREAD

**Issue by qianyoo** [fishaudio/fish-speech#265]
wsl2 Ubuntu 2204 和 win11使用 [install_env.bat](https://github.com/fishaudio/fish-speech/blob/main/install_env.bat) 构建项目
使用vits默认配置训练都会报如下错误，貌似是解析不到指定地址的类

### WSL2 Ubuntu报错信息
![Snipaste_2024-06-06_22-50-30](https://github.com/fishaudio/fish-speech/assets/23526682/9f368d92-ed7c-412e-b0aa-f8c74f00e73b)

```
[2024-06-06 22:49:07,994][__main__][INFO] - [rank: 0] Instantiating datamodule <fish_speech.datasets.vits.VITSDataModule>
[2024-06-06 22:49:08,008][__main__][INFO] - [rank: 0] Instantiating model <fish_speech.models.vits_decoder.VITSDecoder>
/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
[2024-06-06 22:49:11,469][fish_speech.utils.utils][ERROR] - [rank: 0]
Traceback (most recent call last):
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/root/anaconda3/fish-speech/fish-speech-1.1.0/fish_speech/models/vits_decoder/modules/models.py", line 476, in __init__
    self.vq = VQEncoder()
  File "/root/anaconda3/fish-speech/fish-speech-1.1.0/fish_speech/models/vits_decoder/modules/vq_encoder.py", line 41, in __init__
    torch.load("checkpoints/vq-gan-group-fsq-2x1024.pth", map_location="cpu"),
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/vq-gan-group-fsq-2x1024.pth'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/fish-speech/fish-speech-1.1.0/fish_speech/utils/utils.py", line 66, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/root/anaconda3/fish-speech/fish-speech-1.1.0/fish_speech/train.py", line 56, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'fish_speech.models.vits_decoder.modules.models.SynthesizerTrn':
FileNotFoundError(2, 'No such file or directory')
full_key: model.generator
[2024-06-06 22:49:11,472][fish_speech.utils.utils][INFO] - [rank: 0] Output dir: results/vits_20240606_040911
Error executing job with overrides: ['project=vits_20240606_040911', 'ckpt_path=checkpoints/vits_decoder_v1.1.ckpt', 'trainer.strategy.process_group_backend=nccl', 'tokenizer.pretrained_model_name_or_path=checkpoints', 'model.optimizer.lr=1e-4', 'trainer.max_steps=100000', 'data.num_workers=4', 'data.batch_size=8', 'data.val_batch_size=4', 'trainer.precision=32', 'trainer.val_check_interval=100', 'train_dataset.filelist=/root/anaconda3/fish-speech/fish-speech-1.1.0/data/vq_train_filelist.txt', 'val_dataset.filelist=/root/anaconda3/fish-speech/fish-speech-1.1.0/data/vq_val_filelist.txt']
Error in call to target 'fish_speech.models.vits_decoder.modules.models.SynthesizerTrn':
FileNotFoundError(2, 'No such file or directory')

```

### win11 报错信息

```
[2024-06-06 20:13:40,022][__main__][INFO] - [rank: 0] Instantiating datamodule <fish_speech.datasets.vits.VITSDataModule>
[2024-06-06 20:13:40,040][__main__][INFO] - [rank: 0] Instantiating model <fish_speech.models.vits_decoder.VITSDecoder>
[2024-06-06 20:13:41,187][fish_speech.utils.utils][ERROR] - [rank: 0] 
Traceback (most recent call last):
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'fish_speech.models.vits_decoder.modules' has no attribute 'models'. Did you mean: 'modules'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\utils.py", line 650, in _locate
    obj = import_module(mod)
  File "E:\AI\global\fish-speech\fishenv\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\global\fish-speech\fish_speech\models\vits_decoder\modules\models.py", line 11, in <module>
    from .vq_encoder import VQEncoder
  File "E:\AI\global\fish-speech\fish_speech\models\vits_decoder\modules\vq_encoder.py", line 6, in <module>
    from fish_speech.models.vqgan.modules.fsq import DownsampleFiniteScalarQuantize
  File "E:\AI\global\fish-speech\fish_speech\models\vqgan\modules\fsq.py", line 7, in <module>
    from vector_quantize_pytorch import GroupedResidualFSQ
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\vector_quantize_pytorch\__init__.py", line 2, in <module>
    from vector_quantize_pytorch.residual_vq import ResidualVQ, GroupedResidualVQ
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\vector_quantize_pytorch\residual_vq.py", line 13, in <module>
    from einx import get_at
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\einx\__init__.py", line 5, in <module>
    from . import backend
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\einx\backend\__init__.py", line 1, in <module>
    from .register import register_for_module, register, get, backends, numpy
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\einx\backend\register.py", line 50, in <module>
    register_for_module("torch", _torch.create)
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\einx\backend\register.py", line 19, in register_for_module
    register(backend_factory())
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\einx\backend\_torch.py", line 82, in create
    import torch._dynamo as _dynamo
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\torch\_dynamo\__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\torch\_dynamo\convert_frame.py", line 41, in <module>
    from . import config, exc, trace_rules
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\torch\_dynamo\exc.py", line 11, in <module>
    from .utils import counters
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\torch\_dynamo\utils.py", line 1031, in <module>
    if has_triton_package():
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\torch\utils\_triton.py", line 8, in has_triton_package
    import triton
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\__init__.py", line 8, in <module>
    from .runtime import (
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune, heuristics)
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\runtime\autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\language\__init__.py", line 6, in <module>
    from .standard import (
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\language\standard.py", line 3, in <module>
    from ..runtime.jit import jit
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\runtime\jit.py", line 10, in <module>
    from ..runtime.driver import driver
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\backends\__init__.py", line 43, in _discover_backends
    compiler = _load_module(name, os.path.join(root, name, 'compiler.py'))
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\backends\nvidia\compiler.py", line 3, in <module>
    from triton.backends.nvidia.driver import CudaUtils
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\triton\backends\nvidia\driver.py", line 18, in <module>
    library_dir += [os.path.join(os.environ.get("CUDA_PATH"), "lib", "x64")]
  File "E:\AI\global\fish-speech\fishenv\env\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'fish_speech.models.vits_decoder.modules.models.SynthesizerTrn':
TypeError('expected str, bytes or os.PathLike object, not NoneType')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\AI\global\fish-speech\fish_speech\utils\utils.py", line 66, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "E:\AI\global\fish-speech\fish_speech\train.py", line 56, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "E:\AI\global\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'fish_speech.models.vits_decoder.modules.models.SynthesizerTrn', set env var HYDRA_FULL_ERROR=1 to see chained exception.
```

**Comment by qianyoo** [comment]
都是使用 vits默认配置进行训练的报错信息

**Comment by AnyaCoder** [comment]
win11下点击`start.bat`下载模型，

**Comment by qianyoo** [comment]
> win11下点击`start.bat`下载模型，

启动就是使用的 start.bat

**Comment by AnyaCoder** [comment]
到这里下载20240525重新做一次：https://hf-mirror.com/SpicyqSama007/fish-speech-packed/tree/main

**Comment by chwyxy** [comment]
您好，请问我推理也报这个错误，如何解决呢，加载vits模型报错
![image](https://github.com/fishaudio/fish-speech/assets/65377976/125c70d3-b9c4-40c4-943b-6666b7fd6e22)

**Comment by qianyoo** [comment]
> 您好，请问我推理也报这个错误，如何解决呢，加载vits模型报错 ![image](https://private-user-images.githubusercontent.com/65377976/339345345-125c70d3-b9c4-40c4-943b-6666b7fd6e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDIxMTQsIm5iZiI6MTcxODYwMTgxNCwicGF0aCI6Ii82NTM3Nzk3Ni8zMzkzNDUzNDUtMTI1YzcwZDMtYjljNC00MGM0LTk0M2ItNjY2NmI3ZmQ2ZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA1MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZjUyMmUxZjMxMGI0YzBmOGMyNzRjMWM1OGIxNWE1N2I3MGMwMDUxZGFiMjQ4MTJlYjY0OGRhYjgzNmI3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e_M3k67WkxkXZK5pVNmtTin30rvZR_WdxrE4z_KdeIw)

前面大佬回答的
> 到这里下载20240525重新做一次：https://hf-mirror.com/SpicyqSama007/fish-speech-packed/tree/main
