### ISSUE TITLE
[BUG]打开推理服务器错误。TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by qinyu04551** [fishaudio/fish-speech#272]
使用的是fish-speech-1.1.1版本包
欢迎页面底下的版本信息：version:  •  python: 3.10.14  •  torch: 2.4.0.dev20240427+cu121 
安装步骤是安装官网介绍安装的
欢迎页面可以进入，只是勾选“打开推理服务器”会报错误，直接报错：
`Traceback (most recent call last):
  File "F:\download\Firefox\fish-speech-1.1.1\tools\webui.py", line 21, in <module>
    from tools.api import decode_vq_tokens, encode_reference
  File "F:\download\Firefox\fish-speech-1.1.1\tools\api.py", line 38, in <module>
    from tools.llama.generate import (
  File "F:\download\Firefox\fish-speech-1.1.1\tools\llama\generate.py", line 14, in <module>
    import torch._dynamo.config
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\torch\_dynamo\__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\torch\_dynamo\convert_frame.py", line 41, in <module>
    from . import config, exc, trace_rules
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\torch\_dynamo\exc.py", line 11, in <module>
    from .utils import counters
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\torch\_dynamo\utils.py", line 1031, in <module>
    if has_triton_package():
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\torch\utils\_triton.py", line 8, in has_triton_package
    import triton
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\__init__.py", line 8, in <module>
    from .runtime import (
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune, heuristics)
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\runtime\autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\language\__init__.py", line 6, in <module>
    from .standard import (
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\language\standard.py", line 3, in <module>
    from ..runtime.jit import jit
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\runtime\jit.py", line 10, in <module>
    from ..runtime.driver import driver
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\backends\__init__.py", line 43, in _discover_backends
    compiler = _load_module(name, os.path.join(root, name, 'compiler.py'))
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\backends\nvidia\compiler.py", line 3, in <module>
    from triton.backends.nvidia.driver import CudaUtils
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\site-packages\triton\backends\nvidia\driver.py", line 18, in <module>
    library_dir += [os.path.join(os.environ.get("CUDA_PATH"), "lib", "x64")]
  File "F:\download\Firefox\fish-speech-1.1.1\fishenv\env\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType`
请问是哪里有错呢，或者有没有参考的地方

**Comment by qinyu04551** [comment]
已经解决，是我没有安装”CUDA Toolkit“这个软件，所以 os.environ.get("CUDA_PATH")获取值就报错
