### ISSUE TITLE
再执行lora模型合并的时候 size不同的问题

### ISSUE THREAD

**Issue by hotdogarea** [fishaudio/fish-speech#285]
如下 在与lora合并的时候发生以下问题

**Comment by hotdogarea** [comment]
> copying a param with shape torch.Size([8, 1024]) from checkpoint, the shape in current model is torch.Size([8, 1536]).
> 
> ![image](https://private-user-images.githubusercontent.com/11146882/341501091-496a2c86-1c67-4f58-a36e-63995d55b842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDMyNzQsIm5iZiI6MTcxODkwMjk3NCwicGF0aCI6Ii8xMTE0Njg4Mi8zNDE1MDEwOTEtNDk2YTJjODYtMWM2Ny00ZjU4LWEzNmUtNjM5OTVkNTViODQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE3MDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZTk1MTg5NzQ0MzdkMGVjMDQ4NTE2NTY3MGJkMzMyNjk1MjkxMjc0YzM1Yzk3ZjdiZDAzMTc2NTlkNjBiMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9LduTwoAAs_wjpmxj9aAkhYqfCZ2ox3TzBg6sMh4UXg)

使用的是text2semantic-sft-large-v1.1-4k.pth 与该模型merge

**Comment by hotdogarea** [comment]
024-06-21 01:03:51.276 | INFO     | __main__:merge:66 - Found 258 keys in llama model
2024-06-21 01:03:51.276 | INFO     | __main__:merge:67 - Found 308 keys in lora model
Traceback (most recent call last):
  File "H:\AIaudio_Live\fish-speech\tools\llama\merge_lora.py", line 79, in <module>
    merge()
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "H:\AIaudio_Live\fish-speech\tools\llama\merge_lora.py", line 70, in merge
    llama_model.load_state_dict(merged_state_dict, strict=True)
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\torch\nn\modules\module.py", line 2191, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DualARTransformer:

**Comment by hotdogarea** [comment]
我重新训练了lora之后merge成功，但在推理时报错
提示ValueError: Invalid model size

 Merging checkpoints/text2semantic-sft-medium-v1.1-4k.pth and H:\AIaudio_Live\fish-speech\results\lora_text2semantic_medium_20240621_041324\checkpoints\step_000001000.ckpt into checkpoints/mitao1000steps.ckpt with configs dual_ar_2_codebook_medium and r_8_alpha_16
2024-06-21 08:54:50.772 | INFO     | __main__:merge:33 - Loaded llama model with config dual_ar_2_codebook_medium
2024-06-21 08:54:50.831 | INFO     | __main__:merge:40 - Loaded lora model with config LoraConfig(r=8, lora_alpha=16, lora_dropout=0.0)
2024-06-21 08:54:52.908 | INFO     | __main__:merge:43 - Merged model setup complete
2024-06-21 08:54:53.254 | INFO     | __main__:merge:66 - Found 216 keys in llama model
2024-06-21 08:54:53.255 | INFO     | __main__:merge:67 - Found 308 keys in lora model
2024-06-21 08:54:53.382 | INFO     | __main__:merge:71 - Merged model loaded
2024-06-21 08:54:54.616 | INFO     | __main__:merge:75 - Merged model saved to checkpoints/mitao1000steps.ckpt
Traceback (most recent call last):
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "H:\AIaudio_Live\fish-speech\fishenv\env\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "h:\AIaudio_Live\fish-speech\fish_speech\webui\manage.py", line 152, in change_llama_config
    raise ValueError("Invalid model size")
ValueError: Invalid model size

**Comment by Naozumi520** [comment]
The first issue is that you used "dual_ar_2_codebook_medium" while merging the model.

You should use "dual_ar_2_codebook_large" instead, as dim for medium is 1024, and large is 1536.

**Comment by hotdogarea** [comment]
the second issue： i just saw the same question in other issues！ &nbsp;i rename the model to medium.ckpt。successfully worked!&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Naozumi ***@***.***&gt;
发送时间: 2024年6月21日 09:18
收件人: fishaudio/fish-speech ***@***.***&gt;
抄送: hotdogarea ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[fishaudio/fish-speech] 再执行lora模型合并的时候 size不同的问题 (Issue #285)





 
The first issue is that you used "dual_ar_2_codebook_medium" while merging the model.
 
You should use "dual_ar_2_codebook_large" instead, as dim for medium is 1024, and large is 1536.
