### ISSUE TITLE
[BUG] Failed to finetune llama: cannot reshape tensor of 0 elements into shape [0, 2, 16, -1, 2] because the unspecified dimension size -1 can be any value and is ambiguous

### ISSUE THREAD

**Issue by jinqiupeter** [fishaudio/fish-speech#287]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**
An error occurred from the command line when starting training llama from WEBUI:

**To Reproduce**

**Expected behavior**

**Screenshots / log**
If applicable, add screenshots / logs to help explain your problem.
```
Sanity Checking: |                                                          | 0/? [00:00<?, ?it/s][2024-06-21 01:23:21,852][fish_speech.datasets.text][INFO] - [rank: 0] Reading 2 / 1 files
[2024-06-21 01:23:21,852][fish_speech.datasets.text][INFO] - [rank: 0] Reading 1 / 1 files
[2024-06-21 01:23:21,852][fish_speech.datasets.text][INFO] - [rank: 0] Reading 1 / 1 files
[2024-06-21 01:23:21,853][fish_speech.datasets.text][INFO] - [rank: 0] Reading 1 / 1 files
[2024-06-21 01:23:21,853][fish_speech.datasets.text][INFO] - [rank: 0] Read total 1 groups of data
[2024-06-21 01:23:21,853][fish_speech.datasets.text][INFO] - [rank: 0] Read total 1 groups of data
[2024-06-21 01:23:21,854][fish_speech.datasets.text][INFO] - [rank: 0] Read total 1 groups of data
[2024-06-21 01:23:21,854][fish_speech.datasets.text][INFO] - [rank: 0] Read total 2 groups of data
Sanity Checking DataLoader 0:   0%|                                         | 0/2 [00:00<?, ?it/s][2024-06-21 01:23:23,069][fish_speech.utils.utils][ERROR] - [rank: 0] 
Traceback (most recent call last):
  File "/media/peter/Data/fish-speech/fish_speech/utils/utils.py", line 66, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/media/peter/Data/fish-speech/fish_speech/train.py", line 108, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1028, in _run_stage
    self._run_sanity_check()
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1057, in _run_sanity_check
    val_loop.run()
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 311, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 410, in validation_step
    return self._forward_redirection(self.model, self.lightning_module, "validation_step", *args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 640, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 633, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/media/peter/Data/fish-speech/fish_speech/models/text2semantic/lit_module.py", line 296, in validation_step
    return self._step(batch, batch_idx, "val")
  File "/media/peter/Data/fish-speech/fish_speech/models/text2semantic/lit_module.py", line 126, in _step
    outputs = self.model(
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/peter/Data/fish-speech/fish_speech/models/text2semantic/llama.py", line 350, in forward
    x = layer(x, fast_freqs_cis, fast_mask)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/peter/Data/fish-speech/fish_speech/models/text2semantic/llama.py", line 413, in forward
    h = x + self.attention(self.attention_norm(x), freqs_cis, mask, input_pos)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/peter/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/peter/Data/fish-speech/fish_speech/models/text2semantic/llama.py", line 460, in forward
    q = apply_rotary_emb(q, freqs_cis)
  File "/media/peter/Data/fish-speech/fish_speech/models/text2semantic/llama.py", line 558, in apply_rotary_emb
    xshaped = x.float().reshape(*x.shape[:-1], -1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 2, 16, -1, 2] because the unspecified dimension size -1 can be any value and is ambiguous
[2024-06-21 01:23:23,070][fish_speech.utils.utils][INFO] - [rank: 0] Output dir: results/text2semantic_finetune_dual_ar
Error executing job with overrides: ['project=text2semantic_finetune_dual_ar', 'ckpt_path=checkpoints/text2semantic-sft-medium-v1.1-4k.pth', 'trainer.strategy.process_group_backend=nccl', 'model@model.model=dual_ar_2_codebook_medium', 'tokenizer.pretrained_model_name_or_path=checkpoints', "train_dataset.proto_files=['data/quantized-dataset-ft']", "val_dataset.proto_files=['data/quantized-dataset-ft']", 'model.optimizer.lr=1e-5', 'trainer.max_steps=1000', 'data.num_workers=4', 'data.batch_size=8', 'max_length=2048', 'trainer.precision=bf16-true', 'trainer.val_check_interval=100', 'trainer.accumulate_grad_batches=1', 'train_dataset.use_speaker=0.5']
```

**Additional context**
I trained with two wav files in the same Speaker folder

**Comment by jinqiupeter** [comment]
Can someone please help?

**Comment by AnyaCoder** [comment]
2 wav files有点少。。

**Comment by jinqiupeter** [comment]
第一个wav是30分钟，第二个8分钟，是不是要切割？

**Comment by AnyaCoder** [comment]
切成1~10s左右的音频

**Comment by jinqiupeter** [comment]
果然是因为没有切分，现在切成小段可以训练了。 谢谢 @AnyaCoder ！

**Comment by chaoqunxie** [comment]
> 果然是因为没有切分，现在切成小段可以训练了。谢谢 ！

不能自动切割有点难受
