### ISSUE TITLE
[BUG]Failed to install the samplerate dependency

### ISSUE THREAD

**Issue by moxiegushi** [fishaudio/fish-speech#290]
can anyone help？ @leng-yue 
Building wheel for samplerate (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for samplerate (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/root/miniconda3/envs/musev/bin/cmake", line 33, in <module>
          sys.exit(load_entry_point('cmake', 'console_scripts', 'cmake')())
        File "/root/miniconda3/envs/musev/bin/cmake", line 22, in importlib_load_entry_point
          for entry_point in distribution(dist_name).entry_points
        File "/root/miniconda3/envs/musev/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
          return Distribution.from_name(distribution_name)
        File "/root/miniconda3/envs/musev/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
          raise PackageNotFoundError(name)
      importlib.metadata.PackageNotFoundError: No package metadata was found for cmake
      Traceback (most recent call last):
        File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 129, in <module>
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-isps7uyn/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 121, in build_extension
        File "/root/miniconda3/envs/musev/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-mdi259kj/samplerate_bfc4a5d2dd9b45348c0fd1597bd7f294', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-mdi259kj/samplerate_bfc4a5d2dd9b45348c0fd1597bd7f294/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/root/miniconda3/envs/musev/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DPACKAGE_VERSION_INFO=0.2.1']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for samplerate
Successfully built fish-speech
Failed to build samplerate
ERROR: Could not build wheels for samplerate, which is required to install pyproject.toml-based projects

**Comment by leng-yue** [comment]
Check #211
