### ISSUE TITLE
[BUG]vqgan inference error

### ISSUE THREAD

**Issue by moxiegushi** [fishaudio/fish-speech#292]
It seems that a folder named "models" is missing, hwo could i get it ? @leng-yue please help!!!

`Traceback (most recent call last):
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'fish_speech.models' has no attribute 'vqgan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/root/miniconda3/envs/musev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/fish-speech/fish_speech/models/vqgan/__init__.py", line 1, in <module>
    from .lit_module import VQGAN
  File "/root/fish-speech/fish_speech/models/vqgan/lit_module.py", line 13, in <module>
    from fish_speech.models.vqgan.modules.discriminator import Discriminator
  File "/root/fish-speech/fish_speech/models/vqgan/modules/discriminator.py", line 3, in <module>
    from torch.nn.utils.parametrizations import weight_norm
ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations' (/root/miniconda3/envs/musev/lib/python3.10/site-packages/torch/nn/utils/parametrizations.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'fish_speech.models.vqgan.VQGAN':
ImportError("cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations' (/root/miniconda3/envs/musev/lib/python3.10/site-packages/torch/nn/utils/parametrizations.py)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/fish-speech/tools/vqgan/inference.py", line 118, in <module>
    main()
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/fish-speech/tools/vqgan/inference.py", line 66, in main
    model = load_model(config_name, checkpoint_path, device=device)
  File "/root/fish-speech/tools/vqgan/inference.py", line 26, in load_model
    model: LightningModule = instantiate(cfg.model)
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/miniconda3/envs/musev/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'fish_speech.models.vqgan.VQGAN', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model`

**Comment by AnyaCoder** [comment]
手动下载vqgan的ckpt文件放到`checkpoints`下.
https://huggingface.co/fishaudio/fish-speech-1/tree/main
找text2semantic-*-v1.1.ckpt下载

**Comment by moxiegushi** [comment]
> 手动下载vqgan的ckpt文件放到`checkpoints`下. https://huggingface.co/fishaudio/fish-speech-1/tree/main 找text2semantic-*-v1.1.ckpt下载

<img width="447" alt="image" src="https://github.com/fishaudio/fish-speech/assets/25003847/3c92f761-a708-491e-bbad-407e826b58ef">
 @AnyaCoder  多谢解答！模型文件都下载好了，但还是有这个问题
