### ISSUE TITLE
[BUG]不管是训练VQGAN 还是训练VITS都报错

### ISSUE THREAD

**Issue by klossm** [fishaudio/fish-speech#297]
如果是因为配置问题那直接可以关了，
WIN10 64位系统，配置1070TI 8G显存 16G内存 ，训练Bert-VITS2和 GPT-SoVITS 都没问题，就是在训练Fish-Speech时候出了问题，
不管是训练VQGAN 还是训练VITS都是这种报错，训练参数哪怕修改为：bf16mixed，数据加载进程数1，批次大小1，验证批次大小1，都是报错，哪怕我的训练数据只用到5条也是如此。checkpoints重新下过，排除权重下载损坏问题，torch torchvision torchaudio重新安装过，换过版本都不行，HYDRA的依赖也重新安装过依旧是不行，下面是报错信息。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "M:\ai\fish-speech\fish_speech\utils\utils.py", line 66, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "M:\ai\fish-speech\fish_speech\train.py", line 108, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\launchers\subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 986, in _run
    results = self._run_stage()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1028, in _run_stage
    self._run_sanity_check()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1057, in _run_sanity_check
    val_loop.run()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\utilities\combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\utilities\combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 629, in __next__
    data = self._next_data()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 1326, in _next_data
    idx, data = self._get_data()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 1292, in _get_data
    success, data = self._try_get_data()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 1143, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 1936, 18624, 24460, 6344) exited unexpectedly
[2024-06-28 14:40:26,740][fish_speech.utils.utils][INFO] - [rank: 0] Output dir: results/vits_20240628_143831
Error executing job with overrides: ['project=vits_20240628_143831', 'ckpt_path=checkpoints\\vits_decoder_v1.1.ckpt', 'trainer.strategy.process_group_backend=gloo', 'tokenizer.pretrained_model_name_or_path=checkpoints', 'model.optimizer.lr=1e-4', 'trainer.max_steps=1000', 'data.num_workers=4', 'data.batch_size=2', 'data.val_batch_size=2', 'trainer.precision=bf16-mixed', 'trainer.val_check_interval=500', 'train_dataset.filelist=M:\\ai\\fish-speech\\data\\vq_train_filelist.txt', 'val_dataset.filelist=M:\\ai\\fish-speech\\data\\vq_val_filelist.txt']
Traceback (most recent call last):
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 1130, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "M:\ai\fish-speech\fishenv\env\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "M:\ai\fish-speech\fish_speech\train.py", line 135, in main
    train(cfg)
  File "M:\ai\fish-speech\fish_speech\utils\utils.py", line 77, in wrap
    raise ex
  File "M:\ai\fish-speech\fish_speech\utils\utils.py", line 66, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "M:\ai\fish-speech\fish_speech\train.py", line 108, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\launchers\subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 986, in _run
    results = self._run_stage()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1028, in _run_stage
    self._run_sanity_check()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1057, in _run_sanity_check
    val_loop.run()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\utilities\combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\utilities\combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 629, in __next__
    data = self._next_data()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 1326, in _next_data
    idx, data = self._get_data()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 1292, in _get_data
    success, data = self._try_get_data()
  File "M:\ai\fish-speech\fishenv\env\lib\site-packages\torch\utils\data\dataloader.py", line 1143, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 1936, 18624, 24460, 6344) exited unexpectedly

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by FRO4TEN** [comment]
请问解决了吗，方法是？
