### ISSUE TITLE
[BUG]启动API接口报错 ```TypeError: generate_long() got an unexpected keyword argument 'tokenizer' ``` 

### ISSUE THREAD

**Issue by online2311** [fishaudio/fish-speech#305]
启动API接口报错,同样的方法启动webui 没问题。
```
root@GPU-2080Tix4:/exp# python -m tools.api --half --listen 0.0.0.0:8000 --worker 4 --compile
2024-07-03 01:16:44.081 | INFO     | __main__:<module>:418 - Loading Llama model...
2024-07-03 01:17:20.094 | INFO     | tools.llama.generate:load_model:366 - Restored model from checkpoint
2024-07-03 01:17:20.094 | INFO     | tools.llama.generate:load_model:370 - Using DualARTransformer
2024-07-03 01:17:20.095 | INFO     | tools.llama.generate:load_model:376 - Compiling function...
2024-07-03 01:17:21.508 | INFO     | __main__:<module>:426 - Llama model loaded, loading VQ-GAN model...
2024-07-03 01:17:24.781 | INFO     | tools.vqgan.inference:load_model:44 - Loaded model: <All keys matched successfully>
2024-07-03 01:17:24.782 | INFO     | __main__:<module>:434 - VQ-GAN model loaded, warming up...
2024-07-03 01:17:24.783 | INFO     | __main__:load_json:157 - Not using a json file
2024-07-03 01:17:24.783 | INFO     | __main__:encode_reference:108 - No reference audio provided
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/exp/tools/api.py", line 437, in <module>
    list(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/exp/tools/api.py", line 263, in inference
    raise result.response
  File "/exp/tools/llama/generate.py", line 590, in worker
    for chunk in generate_long(
TypeError: generate_long() got an unexpected keyword argument 'tokenizer'
```

**Comment by AnyaCoder** [comment]
PR中已修复
