### ISSUE TITLE
1.2版本，windows下启动start.bat时报错：cannot import name 'RootModel' from 'pydantic'[BUG]

### ISSUE THREAD

**Issue by DLSeed** [fishaudio/fish-speech#317]
很顺利install_env.bat完成运行时安装，最后Success
点击start.bat自动下载完成各个模型，然后运行时报错，进入不了gradio界面：

Debug: flags = --listen 0.0.0.0:8000 --llama-checkpoint-path "checkpoints/fish-speech-1.2" --decoder-checkpoint-path "checkpoints/fish-speech-1.2/firefly-gan-vq-fsq-4x1024-42hz-generator.pth" --decoder-config-name firefly_gan_vq

Next launch the page...
Traceback (most recent call last):
  File "C:\Github\fish-speech\fish_speech\webui\manage.py", line 14, in <module>
    import gradio as gr
  File "C:\Github\fish-speech\fishenv\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Github\fish-speech\fishenv\env\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Github\fish-speech\fishenv\env\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "C:\Github\fish-speech\fishenv\env\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Github\fish-speech\fishenv\env\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "C:\Github\fish-speech\fishenv\env\lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio import utils, wasm_utils
  File "C:\Github\fish-speech\fishenv\env\lib\site-packages\gradio\utils.py", line 55, in <module>
    from gradio.data_classes import FileData
  File "C:\Github\fish-speech\fishenv\env\lib\site-packages\gradio\data_classes.py", line 19, in <module>
    from pydantic import BaseModel, RootModel, ValidationError
ImportError: cannot import name 'RootModel' from 'pydantic' (C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pydantic\__init__.cp310-win_amd64.pyd)
Press any key to continue . . .

**Comment by AnyaCoder** [comment]
C:\Users\admin\AppData\Roaming\Python\Python310
找一下系统环境变量里的这个路径，删除掉。

**Comment by DLSeed** [comment]
> C:\Users\admin\AppData\Roaming\Python\Python310 找一下系统环境变量里的这个路径，删除掉。

谢谢，已解决。可能是其他项目遗留的运行时。
