### ISSUE TITLE
clean.txt import error

### ISSUE THREAD

**Issue by gaoxuxu110** [fishaudio/fish-speech#335]
```python
Traceback (most recent call last):
  File "H:\Deepfacelab\Voice\fish-speech\tools\webui.py", line 23, in <module>
    from tools.api import decode_vq_tokens, encode_reference
  File "H:\Deepfacelab\Voice\fish-speech\tools\api.py", line 35, in <module>
    from tools.llama.generate import (
  File "H:\Deepfacelab\Voice\fish-speech\tools\llama\generate.py", line 19, in <module>
    from fish_speech.text import clean_text, split_text
ImportError: cannot import name 'clean_text' from 'fish_speech.text' (H:\Deepfacelab\Voice\fish-speech\fish_speech\text\__init__.py)
```

**Comment by AnyaCoder** [comment]
Describe your procedure.
