### ISSUE TITLE
[BUG]是不是不支持cuda11.6+pytorch1.1.13? windows环境

### ISSUE THREAD

**Issue by blues4347** [fishaudio/fish-speech#340]
D:\App\fish-speech>开启推理_编译版本.bat
Traceback (most recent call last):
  File "D:\App\fish-speech\tools\webui.py", line 21, in <module>
    from tools.api import decode_vq_tokens, encode_reference
  File "D:\App\fish-speech\tools\api.py", line 35, in <module>
    from fish_speech.models.vits_decoder.lit_module import VITSDecoder
  File "D:\App\fish-speech\fish_speech\models\vits_decoder\__init__.py", line 1, in <module>
    from .lit_module import VITSDecoder
  File "D:\App\fish-speech\fish_speech\models\vits_decoder\lit_module.py", line 17, in <module>
    from fish_speech.models.vqgan.utils import (
  File "D:\App\fish-speech\fish_speech\models\vqgan\__init__.py", line 1, in <module>
    from .lit_module import VQGAN
  File "D:\App\fish-speech\fish_speech\models\vqgan\lit_module.py", line 13, in <module>
    from fish_speech.models.vqgan.modules.discriminator import Discriminator
  File "D:\App\fish-speech\fish_speech\models\vqgan\modules\discriminator.py", line 3, in <module>
    from torch.nn.utils.parametrizations import weight_norm
ImportError: cannot import name 'weight_norm' from 'torch.nn.utils.parametrizations' (D:\App\fish-speech\py310\lib\site-packages\torch\nn\utils\parametrizations.py)
Press any key to continue . . .

**Comment by AnyaCoder** [comment]
非官方整合包。
