### ISSUE TITLE
最新版本缺少funasr模块

### ISSUE THREAD

**Issue by gaoxuxu110** [fishaudio/fish-speech#394]
无法进入推理界面
Traceback (most recent call last):
  File "H:\Deepfacelab\Voice\fish-speech-main-9994780351\tools\webui.py", line 23, in <module>
    from tools.api import decode_vq_tokens, encode_reference
  File "H:\Deepfacelab\Voice\fish-speech-main-9994780351\tools\api.py", line 35, in <module>
    from tools.auto_rerank import batch_asr, calculate_wer, is_chinese, load_model
  File "H:\Deepfacelab\Voice\fish-speech-main-9994780351\tools\auto_rerank.py", line 7, in <module>
    from funasr import AutoModel
ModuleNotFoundError: No module named 'funasr'
此外手动安装funasr后, 可以进入推理界面但是推理后再次报错

Traceback (most recent call last):
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\gradio\queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\gradio\utils.py", line 833, in wrapper
    response = f(*args, **kwargs)
  File "H:\Deepfacelab\Voice\fish-speech\tools\webui.py", line 264, in inference_wrapper
    result = inference_with_auto_rerank(
  File "H:\Deepfacelab\Voice\fish-speech\tools\webui.py", line 193, in inference_with_auto_rerank
    zh_model, en_model = load_model()
  File "H:\Deepfacelab\Voice\fish-speech\tools\auto_rerank.py", line 15, in load_model
    zh_model = AutoModel(
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\funasr\auto\auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "H:\Deepfacelab\Voice\fish-speech\fishenv\env\lib\site-packages\funasr\auto\auto_model.py", line 218, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
AssertionError: paraformer-zh is not registered

**Comment by one-pip** [comment]
ModuleNotFoundError: No module named 'funasr'
遇到同样的问题

**Comment by SapphireLab** [comment]
需要 `pip install modelscope` 和 `pip install funasr`,
在 `modelscope=1.16.1` 和 `funasr=1.1.2` 下最新拉取代码能够正常启动.

**Comment by Stardust-minus** [comment]
Fixed, See #395
