### ISSUE TITLE
环境安装报错

### ISSUE THREAD

**Issue by gaoxuxu110** [fishaudio/fish-speech#397]
```python
Obtaining file:///H:/Deepfacelab/Voice/fish-speech-main-10001578751
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      configuration error: `project.dependencies[25]` must be pep508
      DESCRIPTION:
          Project dependency specification according to PEP 508

      GIVEN VALUE:
          "modelscope=1.16.1"

      OFFENDING RULE: 'format'

      DEFINITION:
          {
              "$id": "#/definitions/dependency",
              "title": "Dependency",
              "type": "string",
              "format": "pep508"
          }

      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html

      Traceback (most recent call last):
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 158, in setup
          dist.parse_config_files()
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\dist.py", line 632, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 70, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 135, in read_configuration
          validate(subset, filepath)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-c7wfiv5p\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 59, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.dependencies[25]`.
      configuration error: `project.dependencies[25]` must be pep508
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1183  100  1183    0     0   1829      0 --:--:-- --:--:-- --:--:--  1831
100  530M  100  530M    0     0  5270k      0  0:01:43  0:01:43 --:--:-- 5847k
"OK for triton_windows-0.1.0-py3-none-any.whl"
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing h:\deepfacelab\voice\fish-speech-main-10001578751\triton_windows-0.1.0-py3-none-any.whl
Installing collected packages: triton-windows
Successfully installed triton-windows-0.1.0

Installing:  fish-speech
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///H:/Deepfacelab/Voice/fish-speech-main-10001578751
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      configuration error: `project.dependencies[25]` must be pep508
      DESCRIPTION:
          Project dependency specification according to PEP 508

      GIVEN VALUE:
          "modelscope=1.16.1"

      OFFENDING RULE: 'format'

      DEFINITION:
          {
              "$id": "#/definitions/dependency",
              "title": "Dependency",
              "type": "string",
              "format": "pep508"
          }

      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html

      Traceback (most recent call last):
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 158, in setup
          dist.parse_config_files()
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\dist.py", line 632, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 70, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 135, in read_configuration
          validate(subset, filepath)
        File "H:\Deepfacelab\Voice\fish-speech-main-10001578751\fishenv\pip-build-env-kwcyiiv9\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 59, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.dependencies[25]`.
      configuration error: `project.dependencies[25]` must be pep508
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Environment Check: Success.
Press any key to continue . . .
```

**Comment by Stardust-minus** [comment]
pull最新代码即可
