### ISSUE TITLE
[BUG] 开始推理后报错

### ISSUE THREAD

**Issue by wenzhongtian** [fishaudio/fish-speech#412]
在推理界面点击生成后提示错误，已经按照介绍安装好了环境，一切设置都为默认
我没有任何编程相关知识，如果提出了不适当的问题，请谅解

以下为原信息：
You are using the latest version of funasr-1.1.2
2024-07-22 00:52:53,799 - modelscope - WARNING - Using the master branch is fragile, please use it with caution!
2024-07-22 00:52:53,799 - modelscope - INFO - Use user-specified model revision: master
You are using the latest version of funasr-1.1.2
2024-07-22 00:52:59,948 - modelscope - WARNING - Using the master branch is fragile, please use it with caution!
2024-07-22 00:52:59,948 - modelscope - INFO - Use user-specified model revision: master
Traceback (most recent call last):
  File "I:\fish-speech\fishenv\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "I:\fish-speech\fishenv\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "I:\fish-speech\fishenv\env\lib\site-packages\gradio\blocks.py", line 1897, in process_api
    result = await self.call_function(
  File "I:\fish-speech\fishenv\env\lib\site-packages\gradio\blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\fish-speech\fishenv\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "I:\fish-speech\fishenv\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "I:\fish-speech\fishenv\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "I:\fish-speech\fishenv\env\lib\site-packages\gradio\utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
  File "I:\fish-speech\tools\webui.py", line 264, in inference_wrapper
    result = inference_with_auto_rerank(
  File "I:\fish-speech\tools\webui.py", line 193, in inference_with_auto_rerank
    zh_model, en_model = load_model()
  File "I:\fish-speech\tools\auto_rerank.py", line 20, in load_model
    en_model = AutoModel(
  File "I:\fish-speech\fishenv\env\lib\site-packages\funasr\auto\auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "I:\fish-speech\fishenv\env\lib\site-packages\funasr\auto\auto_model.py", line 192, in build_model
    tokenizer = tokenizer_class(**kwargs.get("tokenizer_conf", {}))
  File "I:\fish-speech\fishenv\env\lib\site-packages\funasr\tokenizer\sentencepiece_tokenizer.py", line 23, in __init__
    self._build_sentence_piece_processor()
  File "I:\fish-speech\fishenv\env\lib\site-packages\funasr\tokenizer\sentencepiece_tokenizer.py", line 32, in _build_sentence_piece_processor
    self.sp.load(self.bpemodel)
  File "I:\fish-speech\fishenv\env\lib\site-packages\sentencepiece\__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "I:\fish-speech\fishenv\env\lib\site-packages\sentencepiece\__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "C:\Users\温中天\.cache\modelscope\hub\iic\speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020\bpe.model": No such file or directory Error #2
![QQ_1721581160199](https://github.com/user-attachments/assets/bd604949-6b3d-4a15-bacb-4e478db4e85f)

**Comment by AnyaCoder** [comment]
需要更新一下代码，你可以通过下载新的代码包覆盖. 已经弃用funasr.

**Comment by wenzhongtian** [comment]
重新覆盖后推理出现了新的报错，由于我极度缺乏相关代码知识，暂且先关闭此议题 o(´д｀o)
