### ISSUE TITLE
[BUG] api推理不支持mp3格式的参考音频

### ISSUE THREAD

**Issue by Jalen-Zhong** [fishaudio/fish-speech#475]
Feel free to ask any kind of questions in the issues page, but please use English since other users may find your questions valuable.

**Describe the bug**

如题

**To Reproduce**

1. 开启api
2. 请求api服务（使用.mp3作为参考音频格式）

**Expected behavior**

**Screenshots / log**

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 398, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/kui/asgi/applications.py", line 163, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/kui/asgi/applications.py", line 118, in app
    return await getattr(self, scope_type)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/kui/asgi/applications.py", line 142, in http
    return await response(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/baize/asgi/responses.py", line 167, in __call__
    chunk = await generator.asend(None)
  File "/usr/local/lib/python3.10/site-packages/baize/asgi/responses.py", line 191, in render_stream
    async for chunk in self.iterable:
  File "/exp/tools/api.py", line 331, in inference_async
    for chunk in inference(req):
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/exp/tools/api.py", line 225, in inference
    prompt_tokens = encode_reference(
  File "/exp/tools/api.py", line 96, in encode_reference
    reference_audio_content = load_audio(
  File "/exp/tools/api.py", line 89, in load_audio
    audio, _ = librosa.load(reference_audio, sr=sr, mono=True)
  File "/usr/local/lib/python3.10/site-packages/librosa/core/audio.py", line 186, in load
    raise exc
  File "/usr/local/lib/python3.10/site-packages/librosa/core/audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.10/site-packages/librosa/core/audio.py", line 209, in __soundfile_load
    context = sf.SoundFile(path)
  File "/usr/local/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.10/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening <_io.BytesIO object at 0x7efe83e09c10>: Format not recognised.
```

**Additional context**
看样子实在解码的过程中出了问题：`audio, _ = librosa.load(reference_audio, sr=sr, mono=True)`

**Comment by PoTaTo-Mika** [comment]
可以使用ffmpeg或者其它各种音频软件转码。

**Comment by AnyaCoder** [comment]
#482 已修复
