### ISSUE TITLE
[BUG] 无法打开WebUI

### ISSUE THREAD

**Issue by ejiandan** [fishaudio/fish-speech#505]
ERROR: The process "2236" not found.
2024-08-31 21:52:44.430 | INFO     | __main__:clean_infer_cache:146 - C:\Users\ADMINI~1\AppData\Local\Temp\gradio was not found
Traceback (most recent call last):
  File "D:\fish-speech-1.2\tools\webui.py", line 23, in <module>
    from tools.api import decode_vq_tokens, encode_reference
  File "D:\fish-speech-1.2\tools\api.py", line 35, in <module>
    from tools.auto_rerank import batch_asr, calculate_wer, is_chinese, load_model
  File "D:\fish-speech-1.2\tools\auto_rerank.py", line 7, in <module>
    from funasr import AutoModel
ModuleNotFoundError: No module named 'funasr'

**Comment by PoTaTo-Mika** [comment]
请执行pip install funasr
另，release版本存在一定的缺陷，建议clone现有仓库。

**Comment by ejiandan** [comment]
pip install funasr
这个执行了的，问题依旧
release版本是在自建环境中运行的？

**Comment by ejiandan** [comment]
搞定！
运行run_cmd.bat，进入环境后执行pip，问题解决。

**Comment by Stardust-minus** [comment]
#515 Change title to English.
