### ISSUE TITLE
The expanded size of the tensor (4096) must match the existing size (35551) at non-singleton dimension 1. Target sizes: [9, 4096]. Tensor sizes: [9, 35551]

### ISSUE THREAD

**Issue by 0smboy** [fishaudio/fish-speech#594]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. installed in colab
2. useTrump_WEF_2018.mp3 as reference audio about 30 mins
3. put them in examples
4.  execute python -m tools.webui  --llama-checkpoint-path ../checkpoints/fish-speech-1.4 --decoder-checkpoint-path ../checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth --decoder-config-name firefly_gan_vq
5. load the reference audio
6. input some text
7. generate

**Comment by AnyaCoder** [comment]
too long references

**Comment by 0smboy** [comment]
ok, i got it

**Comment by zg9uagfv** [comment]
System Info:
ubuntu20.04
python3.10
CUDA Version: 12.4
FishSpeech1.4

I met a similar issue, the log as blow:
`2024-11-06 13:44:39,692 xinference.model.audio.fish_speech 1730377 WARNING Fish speech does not support setting voice: default.

2024-11-06 13:44:39,693 xinference.model.audio.fish_speech 1730377 WARNING stream mode is not implemented.

2024-11-06 13:44:39.693 | INFO | tools.api:encode_reference:133 - No reference audio provided
2024-11-06 13:44:39.702 | INFO | tools.llama.generate:generate_long:436 - Encoded text: 已为您预约会议，详情如下：
会议室主题:如何进行代码审查
会议室地址:第三会议室
会议开始时间:二零二四年十一月六日二十二时零分
2024-11-06 13:44:39.703 | INFO | tools.llama.generate:generate_long:436 - Encoded text: 会议结束时间:二零二四年十一月七日零时零分

2024-11-06 13:44:39.704 | INFO | tools.llama.generate:generate_long:454 - Generating sentence 1/2 of sample 1/1
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1023/1023 [00:56<00:00, 17.98it/s]
2024-11-06 13:45:36,650 xinference.core.model 1730377 ERROR [request 36e9785a-9c02-11ef-8d96-9cc2c4626bed] Leave speech, error: The expanded size of the tensor (968) must match the existing size (1023) at non-singleton dimension 1. Target sizes: [9, 968]. Tensor sizes: [9, 1023], elapsed time: 56 s
Traceback (most recent call last):
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/utils.py", line 78, in wrapped
ret = await func(*args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 854, in speech
return await self._call_wrapper_binary(
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 520, in _call_wrapper_binary
return await self._call_wrapper("binary", fn, *args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 122, in _async_wrapper
return await fn(*args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 541, in _call_wrapper
ret = await asyncio.to_thread(fn, *args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/asyncio/threads.py", line 25, in to_thread
return await loop.run_in_executor(None, func_call)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/audio/fish_speech.py", line 211, in speech
result = list(
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
response = gen.send(None)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/audio/fish_speech.py", line 164, in _inference
raise Exception(str(result.response))
Exception: The expanded size of the tensor (968) must match the existing size (1023) at non-singleton dimension 1. Target sizes: [9, 968]. Tensor sizes: [9, 1023]
2024-11-06 13:45:36,660 xinference.api.restful_api 1728531 ERROR [address=0.0.0.0:44253, pid=1730377] The expanded size of the tensor (968) must match the existing size (1023) at non-singleton dimension 1. Target sizes: [9, 968]. Tensor sizes: [9, 1023]
Traceback (most recent call last):
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1485, in create_speech
out = await model.speech(
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
return self._process_result_message(result)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
raise message.as_instanceof_cause()
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
result = await self._run_coro(message.message_id, coro)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
return await coro
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in on_receive
return await super().on_receive(message) # type: ignore
File "xoscar/core.pyx", line 558, in on_receive
raise ex
File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.on_receive
async with self._lock:
File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.on_receive
with debug_async_timeout('actor_lock_timeout',
File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.on_receive
result = await result
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 98, in wrapped_func
ret = await fn(self, *args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
r = await func(self, *args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/utils.py", line 78, in wrapped
ret = await func(*args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 854, in speech
return await self._call_wrapper_binary(
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 520, in _call_wrapper_binary
return await self._call_wrapper("binary", fn, *args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 122, in _async_wrapper
return await fn(*args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 541, in _call_wrapper
ret = await asyncio.to_thread(fn, *args, **kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/asyncio/threads.py", line 25, in to_thread
return await loop.run_in_executor(None, func_call)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/audio/fish_speech.py", line 211, in speech
result = list(
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
response = gen.send(None)
File "/home/hs/anaconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/audio/fish_speech.py", line 164, in _inference
raise Exception(str(result.response))
Exception: [address=0.0.0.0:44253, pid=1730377] The expanded size of the tensor (968) must match the existing size (1023) at non-singleton dimension 1. Target sizes: [9, 968]. Tensor sizes: [9, 1023]`

**Comment by AnyaCoder** [comment]
update to latest code by git pull or download 1.4.2
