### ISSUE TITLE
Error when I start the training

### ISSUE THREAD

**Issue by Mixomo** [fishaudio/fish-speech#601]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/fishaudio/fish-speech/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Start the training interface, process the dataset and start the training.

All models are downloaded to their sites and are recognized by fish.

### ✔️ Expected Behavior

I have installed everything to the letter as indicated in the documentation, with no errors, I am in a virtual environment and I get this error when I try to start the training of a model. 

### ❌ Actual Behavior

`Traceback (most recent call last):
  File "J:\fish_audio\fish-speech\fish_speech\train.py", line 7, in <module>
    import hydra
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\hydra\__init__.py", line 5, in <module>
    from hydra import utils
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\hydra\utils.py", line 10, in <module>
    from hydra._internal.utils import (
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\utils.py", line 16, in <module>
    from omegaconf._utils import get_ref_type
ImportError: cannot import name 'get_ref_type' from 'omegaconf._utils' (J:\fish_audio\fish-speech\fishenv\env\lib\site-packages\omegaconf\_utils.py)
`

**Comment by Mixomo** [comment]
Update:

Installing an older version of Omegaconf mitigated the error, but now I have this new error, although already try to downgrade Pydantic to V1 version:

`Traceback (most recent call last):
  File "J:\fish_audio\fish-speech\tools\webui.py", line 24, in <module>
    from fish_speech.utils import autocast_exclude_mps
  File "J:\fish_audio\fish-speech\fish_speech\utils\__init__.py", line 6, in <module>
    from .logging_utils import log_hyperparameters
  File "J:\fish_audio\fish-speech\fish_speech\utils\logging_utils.py", line 1, in <module>
    from lightning.pytorch.utilities import rank_zero_only
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\lightning\__init__.py", line 18, in <module>
    from lightning.app import storage  # noqa: E402
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\lightning\app\__init__.py", line 24, in <module>
    from lightning.app import components  # noqa: E402, F401
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\lightning\app\components\__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\lightning\app\components\database\__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\lightning\app\components\database\client.py", line 22, in <module>
    from lightning.app.components.database.utilities import _GeneralModel
  File "C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\lightning\app\components\database\utilities.py", line 23, in <module>
    from pydantic.main import ModelMetaclass
ImportError: cannot import name 'ModelMetaclass' from 'pydantic.main' (C:\Users\Win10\AppData\Roaming\Python\Python310\site-packages\pydantic\main.py)
`

**Comment by AnyaCoder** [comment]
You may temporarily remove the environment path `C:\Users\Win10\AppData\Roaming\Python\Python310` to ensure that this specific environment does not interfere with your current project.
