### ISSUE TITLE
Streaming output error in webui

### ISSUE THREAD

**Issue by lhpqaq** [fishaudio/fish-speech#642]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

Ubuntu24 
Python 3.10.15
ffmpeg 6.1.1

Same with [doc](https://speech.fish.audio/)

### Steps to Reproduce

Streaming Audio in webui

### ❌ Actual Behavior

error
![bf099c1941ff02208bf0989b895bfa54](https://github.com/user-attachments/assets/102c923b-b7f5-488e-bc5a-af0f73311472)

```
2024-10-30 16:04:55.627 | INFO     | tools.api:decode_vq_tokens:146 - VQ features: torch.Size([8, 136])
[ 1.5735626e-05 -7.1525574e-06 -9.5367432e-07 ...  7.8678131e-05
  5.9127808e-05 -4.6253204e-05]
Traceback (most recent call last):
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/gradio/queueing.py", line 706, in process_events
    response = await route_utils.call_process_api(
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/gradio/blocks.py", line 2043, in process_api
    data = await self.handle_streaming_outputs(
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/gradio/blocks.py", line 1870, in handle_streaming_outputs
    binary_data, output_data = await block.stream_output(
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/gradio/components/audio.py", line 347, in stream_output
    value, duration = await self.covert_to_adts(value)
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/gradio/components/audio.py", line 330, in covert_to_adts
    return await anyio.to_thread.run_sync(Audio._convert_to_adts, data)
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/gradio/components/audio.py", line 321, in _convert_to_adts
    segment = AudioSegment.from_file(io.BytesIO(data))
  File "/home/aim/conda/envs/fish-speech/lib/python3.10/site-packages/pydub/audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 183

Output from ffmpeg/avlib:

ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[cache @ 0x5c694e560a40] Statistics, cache hits:0 cache misses:51
[in#0 @ 0x5c694e5602c0] Error opening input: Invalid data found when processing input
Error opening input file cache:pipe:0.
Error opening input files: Invalid data found when processing input
```

**Comment by Stardust-minus** [comment]
PR Merged.
