### ISSUE TITLE
[BUG] webui.py trying to use CUDA specific code even with CUDA not installed

### ISSUE THREAD

**Issue by Picus303** [fishaudio/fish-speech#691]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

Windows 10, torch==2.5.1

### Steps to Reproduce

1 - Install CPU version of Pytorch
2 - Download source and install
3 - Download models with `huggingface-cli download fishaudio/fish-speech-1.4 --local-dir checkpoints/fish-speech-1.4/`
4 - Run `python tools/webui.py --llama-checkpoint-path checkpoints/fish-speech-1.4 --decoder-checkpoint-path checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth`

### ✔️ Expected Behavior

Launch the webui

### ❌ Actual Behavior

Traceback (most recent call last):
  File "C:\Users\pille\Downloads\fish-speech-1.4.3\tools\webui.py", line 24, in <module>
    from fish_speech.utils import autocast_exclude_mps, set_seed
  File "C:\Users\pille\Downloads\fish-speech-1.4.3\fish_speech\utils\__init__.py", line 4, in <module>
    from .instantiators import instantiate_callbacks, instantiate_loggers
  File "C:\Users\pille\Downloads\fish-speech-1.4.3\fish_speech\utils\instantiators.py", line 5, in <module>
    from pytorch_lightning import Callback
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\pytorch_lightning\__init__.py", line 25, in <module>
    from lightning_fabric.utilities.seed import seed_everything  # noqa: E402
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\lightning_fabric\__init__.py", line 30, in <module>
    from lightning_fabric.fabric import Fabric  # noqa: E402
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\lightning_fabric\fabric.py", line 46, in <module>
    from lightning_fabric.loggers import Logger
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\lightning_fabric\loggers\__init__.py", line 15, in <module>
    from lightning_fabric.loggers.tensorboard import TensorBoardLogger  # noqa: F401
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\lightning_fabric\loggers\tensorboard.py", line 30, in <module>
    from lightning_fabric.wrappers import _unwrap_objects
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\lightning_fabric\wrappers.py", line 38, in <module>
    from torch._dynamo import OptimizedModule
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\_dynamo\__init__.py", line 3, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\_dynamo\convert_frame.py", line 31, in <module>
    from torch._dynamo.utils import CompileTimeInstructionCounter
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\_dynamo\utils.py", line 1320, in <module>
    if has_triton_package():
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\utils\_triton.py", line 9, in has_triton_package
    from triton.compiler.compiler import triton_key
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\__init__.py", line 8, in <module>
    from .runtime import (
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune, heuristics)
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\runtime\autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\language\__init__.py", line 6, in <module>
    from .standard import (
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\language\standard.py", line 3, in <module>
    from ..runtime.jit import jit
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\runtime\jit.py", line 10, in <module>
    from ..runtime.driver import driver
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\backends\__init__.py", line 43, in _discover_backends
    compiler = _load_module(name, os.path.join(root, name, 'compiler.py'))
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\backends\nvidia\compiler.py", line 3, in <module>
    from triton.backends.nvidia.driver import CudaUtils
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\triton\backends\nvidia\driver.py", line 18, in <module>
    library_dir += [os.path.join(os.environ.get("CUDA_PATH"), "lib", "x64")]
  File "C:\Users\pille\anaconda3\envs\start\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Picus303** [comment]
Adding this: I plan to use Fishaudio on Linux with ROCm but just wanted to try it on CPU before.

**Comment by AnyaCoder** [comment]
try to uninstall triton
`pip uninstall triton-windows`

**Comment by Picus303** [comment]
> try to uninstall triton `pip uninstall triton-windows`

I just tried. It seems to be better but a similar problem still appear later:

```
Exception in thread Thread-6 (worker):
Traceback (most recent call last):
  File "C:\Users\pille\anaconda3\envs\start\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\pille\anaconda3\envs\start\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pille\Downloads\fish-speech-1.4.3\tools\llama\generate.py", line 884, in worker
    model, decode_one_token = load_model(
  File "C:\Users\pille\Downloads\fish-speech-1.4.3\tools\llama\generate.py", line 666, in load_model
    model = model.to(device=device, dtype=precision)
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
  File "C:\Users\pille\anaconda3\envs\start\lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

Looks like `device` is forced to `cuda` somewhere without doing the check `device = "cuda" if torch.cuda.is_available() else "cpu"`

**Comment by Picus303** [comment]
I found the problem: almost all argument parsers default the value `device` to `cuda` but don't check if it's even possible. I'll try to submit a PR later.

**Comment by Stardust-minus** [comment]
#693
