### ISSUE TITLE
RuntimeError: cutlassF: no kernel found to launch!

### ISSUE THREAD

**Issue by meowlgm** [fishaudio/fish-speech#7]
The following error occurred when executing the second part of the inference code. How can I resolve this?
```text
Driver Version: 546.33
```
nvcc -V
```text
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
```
```text
Traceback (most recent call last):
  File "/home/meowlgm/fish-speech/tools/llama/generate.py", line 476, in <module>
    main()
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/meowlgm/fish-speech/tools/llama/generate.py", line 440, in main
    y = generate(
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/meowlgm/fish-speech/tools/llama/generate.py", line 237, in generate
    next_token = prefill(
  File "/home/meowlgm/fish-speech/tools/llama/generate.py", line 129, in prefill
    logits = model.forward_generate(x, input_pos)
  File "/home/meowlgm/fish-speech/fish_speech/models/text2semantic/llama.py", line 209, in forward_generate
    return self.compute(x, freqs_cis, mask, input_pos=input_pos)
  File "/home/meowlgm/fish-speech/fish_speech/models/text2semantic/llama.py", line 151, in compute
    x = layer(x, freqs_cis, mask, input_pos=input_pos)
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/meowlgm/fish-speech/fish_speech/models/text2semantic/llama.py", line 223, in forward
    h = x + self.attention(self.attention_norm(x), freqs_cis, mask, input_pos)
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/meowlgm/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/meowlgm/fish-speech/fish_speech/models/text2semantic/llama.py", line 278, in forward
    y = F.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0)
RuntimeError: cutlassF: no kernel found to launch!
```

**Comment by suzhenghang** [comment]
In my environment, set
torch.backends.cuda.enable_mem_efficient_sdp(False)
in addition to
torch.backends.cuda.enable_flash_sdp(False)
improved situation.

**Comment by leng-yue** [comment]
I am only using the math kernel only when you are running inference? Which pytorch and cuda version are you using?

**Comment by faceair** [comment]
I have installed CUDA 12.1 and PyTorch 2.1.0, and I am encountering the same error as well.

```shell
conda install -c "nvidia/label/cuda-12.1.1" cuda
pip3 install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121

Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.zeros(1).cuda()
tensor([0.], device='cuda:0')
>>> torch.cuda.is_available()
True
>>> 
```

**Comment by meowlgm** [comment]
> I am only using the math kernel only when you are running inference? Which pytorch and cuda version are you using?
pytorch: Stable (2.1.2)
CUDA: 12.3

**Comment by leng-yue** [comment]
https://github.com/Lightning-AI/lit-gpt/issues/327#issuecomment-1678527612

Does your GPU supports bf16?

**Comment by leng-yue** [comment]
Added half precision (fp16) inference support, you can add `--half` to inference now.  
Updated document: https://speech.fish.audio/zh/inference/#2-token

**Comment by faceair** [comment]
Thanks, it works.

**Comment by meowlgm** [comment]
> Added half precision (fp16) inference support, you can add `--half` to inference now. Updated document: https://speech.fish.audio/zh/inference/#2-token

It works for me too, thanks.

**Comment by meowlgm** [comment]
> Thanks, it works.

Are you able to generate audio correctly? The audio I generated in the end is silent, without any sound.😟

**Comment by leng-yue** [comment]
This is a known issue (like 20% prob), probably add some regulation later. For now, you can change the num samples to generate more.

**Comment by faceair** [comment]
Hi @leng-yue , when I attempted to finetune Text2Semantic, I encountered the same error. However, the fish_speech/train.py script does not support the passing of a `--half` parameter.

```
python fish_speech/train.py --config-name text2semantic_finetune_spk --half               
usage: train.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE] [--run] [--multirun]
                [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR]
                [--experimental-rerun EXPERIMENTAL_RERUN] [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                [overrides ...]
train.py: error: unrecognized arguments: --half
```

**Comment by leng-yue** [comment]
For text seamntic finetune, you need to edit the config, and change the bf16 to fp16.

**Comment by forwiat** [comment]
It seems nvidia(t4 or v100 ?) doesn't supports, even if you set "torch.backends.cuda.enable_mem_efficient_sdp(False)"and  "torch.backends.cuda.enable_flash_sdp(False)", then will throw error: "error   : Feature '.bf16' requires .target sm_80 or higher". A simple solution is that changing "precision = torch.half if half else torch.bfloat16" in generate.py to "precision = torch.half if half else torch.float16", then it will works. Or you can use A100 to train.
