### ISSUE TITLE
An error occurred during model fine-tuning (KeyError: 'dual_ar') (DDP Error)

### ISSUE THREAD

**Issue by None1024Outlook** [fishaudio/fish-speech#700]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

## Error_1
```bash
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1034, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 736, in __getitem__
    raise KeyError(key)
KeyError: 'dual_ar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 877, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1036, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `dual_ar` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\fish-speech\fish_speech\utils\utils.py", line 69, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "C:\Users\Administrator\Documents\fish-speech\fish_speech\train.py", line 55, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'transformers.models.auto.tokenization_auto.AutoTokenizer.from_pretrained':
ValueError('The checkpoint you are trying to load has model type `dual_ar` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.')
full_key: data.train_dataset.tokenizer
[2024-12-03 22:37:50,875][fish_speech.utils.utils][INFO] - [rank: 0] Output dir: results/Speaker1
Error executing job with overrides: ['project=Speaker1', '+lora@model.model.lora_config=r_8_alpha_16', 'trainer.strategy.process_group_backend=gloo']
Error in call to target 'transformers.models.auto.tokenization_auto.AutoTokenizer.from_pretrained':
ValueError('The checkpoint you are trying to load has model type `dual_ar` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.')
full_key: data.train_dataset.tokenizer

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Error_2
```bash
Epoch 0: |                                                                                                                                             | 1/? [01:23<00:00,  0.01it/s, v_num=8, train/loss=29.50, train/top_5_accuracy=0.012]
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\fish-speech\fish_speech\utils\utils.py", line 69, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "C:\Users\Administrator\Documents\fish-speech\fish_speech\train.py", line 114, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\call.py", line 46, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\launchers\subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 981, in _run
    results = self._run_stage()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1025, in _run_stage
    self.fit_loop.run()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 205, in run
    self.advance()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\training_epoch_loop.py", line 250, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 190, in run
    self._optimizer_step(batch_idx, closure)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 268, in _optimizer_step
    call._call_lightning_module_hook(
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\core\module.py", line 1306, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\core\optimizer.py", line 153, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\ddp.py", line 270, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, closure, model, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 238, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\plugins\precision\precision.py", line 122, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\optim\lr_scheduler.py", line 137, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\optim\optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\optim\optimizer.py", line 91, in _use_grad
    ret = func(self, *args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\optim\adamw.py", line 197, in step
    loss = closure()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\plugins\precision\precision.py", line 108, in _wrap_closure
    closure_result = closure()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 144, in __call__
    self._result = self.closure(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 129, in closure
    step_output = self._step_fn()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 317, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\call.py", line 319, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 389, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 640, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\nn\parallel\distributed.py", line 1639, in forward
    inputs, kwargs = self._pre_forward(*inputs, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\nn\parallel\distributed.py", line 1528, in _pre_forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: It looks like your LightningModule has parameters that were not used in producing the loss returned by training_step. If this is intentional, you must enable the detection of unused parameters in DDP, either by setting the string value `strategy='ddp_find_unused_parameters_true'` or by setting the flag in the strategy with `strategy=DDPStrategy(find_unused_parameters=True)`.
[2024-12-03 23:34:37,583][fish_speech.utils.utils][INFO] - [rank: 0] Output dir: results/Speaker1
Error executing job with overrides: ['project=Speaker1', '+lora@model.model.lora_config=r_8_alpha_16', 'trainer.strategy.process_group_backend=gloo']
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\fish-speech\fish_speech\train.py", line 141, in main
    train(cfg)
  File "C:\Users\Administrator\Documents\fish-speech\fish_speech\utils\utils.py", line 80, in wrap
    raise ex
  File "C:\Users\Administrator\Documents\fish-speech\fish_speech\utils\utils.py", line 69, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "C:\Users\Administrator\Documents\fish-speech\fish_speech\train.py", line 114, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\call.py", line 46, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\launchers\subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 981, in _run
    results = self._run_stage()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1025, in _run_stage
    self.fit_loop.run()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 205, in run
    self.advance()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\training_epoch_loop.py", line 250, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 190, in run
    self._optimizer_step(batch_idx, closure)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 268, in _optimizer_step
    call._call_lightning_module_hook(
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\core\module.py", line 1306, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\core\optimizer.py", line 153, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\ddp.py", line 270, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, closure, model, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 238, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\plugins\precision\precision.py", line 122, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\optim\lr_scheduler.py", line 137, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\optim\optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\optim\optimizer.py", line 91, in _use_grad
    ret = func(self, *args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\optim\adamw.py", line 197, in step
    loss = closure()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\plugins\precision\precision.py", line 108, in _wrap_closure
    closure_result = closure()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 144, in __call__
    self._result = self.closure(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 129, in closure
    step_output = self._step_fn()
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py", line 317, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\trainer\call.py", line 319, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 389, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 640, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\nn\parallel\distributed.py", line 1639, in forward
    inputs, kwargs = self._pre_forward(*inputs, **kwargs)
  File "C:\Users\Administrator\Documents\fish-speech\fishenv\env\lib\site-packages\torch\nn\parallel\distributed.py", line 1528, in _pre_forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: It looks like your LightningModule has parameters that were not used in producing the loss returned by training_step. If this is intentional, you must enable the detection of unused parameters in DDP, either by setting the string value `strategy='ddp_find_unused_parameters_true'` or by setting the flag in the strategy with `strategy=DDPStrategy(find_unused_parameters=True)`.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Epoch 0: |                                                                                                                                             | 1/? [01:23<00:00,  0.01it/s, v_num=8, train/loss=29.50, train/top_5_accuracy=0.012]
```

### Command
```bash
python fish_speech/train.py --config-name text2semantic_finetune \  
       project=Speaker1                                                                                                 \  
       +lora@model.model.lora_config=r_8_alpha_16                                   \  
       trainer.strategy.process_group_backend=gloo
```
### Config
```yaml
defaults:
  - base
  - _self_

project: text2semantic_finetune_dual_ar
max_length: 4096
pretrained_ckpt_path: checkpoints/fish-speech-1.5

# Lightning Trainer
trainer:
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  max_steps: 1000
  precision: bf16-true
  limit_val_batches: 10
  val_check_interval: 100

# Dataset Configuration
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${pretrained_ckpt_path}

# Dataset Configuration
train_dataset:
  _target_: fish_speech.datasets.semantic.AutoTextSemanticInstructionDataset
  proto_files:
    - data/protos
  tokenizer: ${tokenizer}
  causal: true
  max_length: ${max_length}
  use_speaker: false
  interactive_prob: 0.7

val_dataset:
  _target_: fish_speech.datasets.semantic.AutoTextSemanticInstructionDataset
  proto_files:
    - data/protos
  tokenizer: ${tokenizer}
  causal: true
  max_length: ${max_length}
  use_speaker: false
  interactive_prob: 0.7

data:
  _target_: fish_speech.datasets.semantic.SemanticDataModule
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  num_workers: 2
  batch_size: 8
  tokenizer: ${tokenizer}
  max_length: ${max_length}

# Model Configuration
model:
  _target_: fish_speech.models.text2semantic.lit_module.TextToSemantic
  model: 
    _target_: fish_speech.models.text2semantic.llama.BaseTransformer.from_pretrained
    path: ${pretrained_ckpt_path}
    load_weights: true
    max_length: ${max_length}
    lora_config: null

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1e-4
    weight_decay: 0
    betas: [0.9, 0.95]
    eps: 1e-5

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    _partial_: true
    lr_lambda:
      _target_: fish_speech.scheduler.get_constant_schedule_with_warmup_lr_lambda
      _partial_: true
      num_warmup_steps: 10

# Callbacks
callbacks:
  model_checkpoint:
    every_n_train_steps: ${trainer.val_check_interval}

```

## ERROR_2
I saw that the error(ERROR_1) occurred due to a format issue when loading the Tokenizer model. After trying to upgrade and reinstall the transformers library without success, I copied the tokenizer.json and tokenizer_config.json files from Fish Speech v1.4, and the error was resolved.

### Command
```bash
python fish_speech/train.py --config-name text2semantic_finetune \  
       project=Speaker1                                                                                                 \  
       +lora@model.model.lora_config=r_8_alpha_16                                   \  
       trainer.strategy.process_group_backend=gloo
```
### Config
```yaml
defaults:
  - base
  - _self_

project: text2semantic_finetune_dual_ar
max_length: 4096
pretrained_ckpt_path: checkpoints/fish-speech-1.5

# Lightning Trainer
trainer:
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  max_steps: 1000
  precision: bf16-true
  limit_val_batches: 10
  val_check_interval: 100

# Dataset Configuration
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${pretrained_ckpt_path}

# Dataset Configuration
train_dataset:
  _target_: fish_speech.datasets.semantic.AutoTextSemanticInstructionDataset
  proto_files:
    - data/protos
  tokenizer: ${tokenizer}
  causal: true
  max_length: ${max_length}
  use_speaker: false
  interactive_prob: 0.7

val_dataset:
  _target_: fish_speech.datasets.semantic.AutoTextSemanticInstructionDataset
  proto_files:
    - data/protos
  tokenizer: ${tokenizer}
  causal: true
  max_length: ${max_length}
  use_speaker: false
  interactive_prob: 0.7

data:
  _target_: fish_speech.datasets.semantic.SemanticDataModule
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  num_workers: 2
  batch_size: 8
  tokenizer: ${tokenizer}
  max_length: ${max_length}

# Model Configuration
model:
  _target_: fish_speech.models.text2semantic.lit_module.TextToSemantic
  model: 
    _target_: fish_speech.models.text2semantic.llama.BaseTransformer.from_pretrained
    path: ${pretrained_ckpt_path}
    load_weights: true
    max_length: ${max_length}
    lora_config: null

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1e-4
    weight_decay: 0
    betas: [0.9, 0.95]
    eps: 1e-5

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    _partial_: true
    lr_lambda:
      _target_: fish_speech.scheduler.get_constant_schedule_with_warmup_lr_lambda
      _partial_: true
      num_warmup_steps: 10

# Callbacks
callbacks:
  model_checkpoint:
    every_n_train_steps: ${trainer.val_check_interval}

```
After copying the files and rerunning the command, it works, but a new error has occurred. At least the previous error is gone, right? :)
My entire environment setup is written [here](https://blog.nonewiki.top), which might help identify the issue

### ✔️ Expected Behavior

correctly fine-tune

### ❌ Actual Behavior

crash error happened

**Comment by yw0nam** [comment]
I got same error.

Maybe fish-speech 1.5 is not stable yet.

**Comment by Stardust-minus** [comment]
Ver 1.5 has not implemented finetune, only infer was supported.

Plz wait for days :)
