### ISSUE TITLE
偶发 Invalid argument的问题，出现在inference.py -i的环节

### ISSUE THREAD

**Issue by go-mixed** [fishaudio/fish-speech#74]
## 环境：
Ubuntu 22.04

## torch版本
```
torch                     2.1.2
torchaudio                2.1.2
torchmetrics              1.3.0.post0
torchvision               0.16.2
```

## 显卡：
A30
```
cuda_12.2.r12.2

Driver Version: 535.54.03
```

## 操作步骤
源音频阶段，-i wav文件，下面的lzl1音频，后续流程都无法进行下去。
而后续生成阶段（输入别的音频文件后），-i npy文件则会经常会触发，推理文本稍微长点，会必现

```python
# 源音频输入阶段
python tools/vqgan/inference.py \
                                          -i "lzl1.wav" \
                                          --checkpoint-path "checkpoints/vqgan-v1.pth"


# 生成阶段
python tools/vqgan/inference.py \
    -i "codes_0.npy" \
    --checkpoint-path "checkpoints/vqgan-v1.pth"
```

## 音频：
17s
16bit，44100Hz，1411 kbps
[lzl1.zip](https://github.com/fishaudio/fish-speech/files/14046811/lzl1.zip)

## 文本：

```
从小到大，都是别人教你：该做什么，不该做什么，其实，人生，这么复杂，哪里是一句：一份耕耘、一份收获，就可以讲的清楚的呢？遵从内心一次。
```

## 错误详情

```
/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
2024-01-25 04:19:39.209 | INFO     | __main__:main:51 - Restored model from checkpoint
2024-01-25 04:19:39.210 | INFO     | __main__:main:54 - Processing in-place reconstruction of lzl1.wav
2024-01-25 04:19:40.343 | INFO     | __main__:main:62 - Loaded audio with 17.06 seconds
2024-01-25 04:19:41.554 | INFO     | __main__:main:102 - Generated indices of shape torch.Size([4, 368])
2024-01-25 04:19:42.025 | INFO     | __main__:main:126 - VQ Encoded, indices: torch.Size([4, 1, 368, 1]) equivalent to 21.53 Hz
Traceback (most recent call last):
  File "/path/to/fish-speech/tools/vqgan/inference.py", line 147, in <module>
    main()
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/path/to/fish-speech/tools/vqgan/inference.py", line 135, in main
    fake_audios = model.generator(decoded_mels)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/fish-speech/fish_speech/models/vqgan/modules/decoder.py", line 76, in forward
    xs += self.resblocks[i * self.num_kernels + j](x)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/fish-speech/fish_speech/models/vqgan/modules/decoder.py", line 172, in forward
    xt = c1(xt)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Invalid argument
```

**Comment by go-mixed** [comment]
降低声音的采样率到：16bit 22050Hz 352kbps 单声道

如下错误：
```
/root/anaconda3/envs/fish-speech/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
2024-01-25 04:56:29.981 | INFO     | __main__:main:51 - Restored model from checkpoint
2024-01-25 04:56:29.982 | INFO     | __main__:main:54 - Processing in-place reconstruction of lzl1.wav
2024-01-25 04:56:31.088 | INFO     | __main__:main:62 - Loaded audio with 17.06 seconds
2024-01-25 04:56:32.332 | INFO     | __main__:main:102 - Generated indices of shape torch.Size([4, 368])
2024-01-25 04:56:32.852 | INFO     | __main__:main:126 - VQ Encoded, indices: torch.Size([4, 1, 368, 1]) equivalent to 21.53 Hz
python: pthread_mutex_lock.c:438: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
fish: Job 1, 'python tools/vqgan/inference.py…' terminated by signal SIGABRT (Abort)
```

**Comment by leng-yue** [comment]
爆错只有 Invalid argument 没有别的信息么?

**Comment by go-mixed** [comment]
@leng-yue leng-yue 
某些素材，长度在10s以内，问题几乎不出现，
某些素材，长度在20s都没问题

上面的lzl.zip可以说是必现问题
但是一个更长时间的lzl（20s）反而没问题

这在源音频输入阶段、生成阶段都会发生

并且同样的文本，在generate.py后不同的sample中（codes_X.npy），部分能生成，部分报Invalid argument的错误

有些说话较慢的素材，只能切割为短句来生成，不然必现。

总体上感觉超过10s后，问题会特别明显

**Comment by leng-yue** [comment]
我这边测过更长的没遇到问题... 如果没有更多信息的话, 我倾向于是环境问题.. 你换个设备试试?
