### ISSUE TITLE
No such file or directory: 'checkpoints\\fish-speech-1.4'

### ISSUE THREAD

**Issue by SoftologyPro** [fishaudio/fish-speech#748]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

Windows 11

### Steps to Reproduce

1. Install latest 
```
git clone https://github.com/fishaudio/fish-speech
cd fish-speech
call install_env.bat
```
2. Try and run it (with start.bat)
```
Traceback (most recent call last):
  File "D:\FishSpeech\fish-speech\fishenv\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\FishSpeech\fish-speech\fishenv\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\FishSpeech\fish-speech\tools\llama\generate.py", line 912, in worker
    model, decode_one_token = load_model(
  File "D:\FishSpeech\fish-speech\tools\llama\generate.py", line 677, in load_model
    model: Union[NaiveTransformer, DualARTransformer] = BaseTransformer.from_pretrained(
  File "D:\FishSpeech\fish-speech\fish_speech\models\text2semantic\llama.py", line 387, in from_pretrained
    config = BaseModelArgs.from_pretrained(str(path))
  File "D:\FishSpeech\fish-speech\fish_speech\models\text2semantic\llama.py", line 82, in from_pretrained
    with open(path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints\\fish-speech-1.4'
```

Looks like the code still has multiple references to 1.4 that should be 1.5, ie
![image](https://github.com/user-attachments/assets/111dfff2-b70a-4da8-9af6-b40729d93048)

And the models are gated now?  Why?
```
Cannot access gated repo for url https://hf-mirror.com/fishaudio/fish-speech-1.5/resolve/main/gitattributes.
Access to model fishaudio/fish-speech-1.5 is restricted and you are not in the authorized list. Visit https://huggingface.co/fishaudio/fish-speech-1.5 to ask for access.
```
I agreed to the access.  Run it again.  Still fails.
It makes it MUCH easier for people if you do not restrict your models.
Do you have a series of steps I should follow once I agree to access to then use the model with the local UI?
Thanks

### ✔️ Expected Behavior

Not to crash

### ❌ Actual Behavior

It crashes :)

**Comment by None1024Outlook** [comment]
plz use `huggingface-cli login`

**Comment by SoftologyPro** [comment]
> plz use `huggingface-cli login`

OK, that fixes the "cannot access gated repo" issue, but I still get the other error.
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints\fish-speech-1.4'

**Comment by PoTaTo-Mika** [comment]
Please check your file folder / fix the code by change 1.4 to 1.5.

**Comment by SoftologyPro** [comment]
> Please check your file folder / fix the code by change 1.4 to 1.5.

But shouldn't the dev fix the code in the repo?  It is going to fail for anyone who tries it.

**Comment by RASPIAUDIO** [comment]
same here, it seems that your github is still referencing on 1.4, I've tried to replace some thext by 1.5 but there are so many enties in different files!

please help :)

**Comment by RASPIAUDIO** [comment]
ok managed to start the api server you need to in Visual Studio Code look for "1.4" in the all directory and replace all by "1.5" but I will no do a PR as I still have many warnings

**Comment by SoftologyPro** [comment]
So can the dev(s) please fix the 1.4 references now?

**Comment by SoftologyPro** [comment]
I see that some of the 1.4 refs were fixed.  I can now get the UI launching, but there are still refs to 1.4.

When I select the 1.5 models instead, http://127.0.0.1:7862 does not open.  "Firefox can’t establish a connection to the server at 127.0.0.1:7862"

![image](https://github.com/user-attachments/assets/85f84cfb-08a7-467a-b270-9a37141343e6)
