### ISSUE TITLE
404 Client Error: Not Found for url: https://hf-mirror.com/fishaudio/fish-speech-1.5/resolve/main/gitattributes

### ISSUE THREAD

**Issue by NaughtDZ** [fishaudio/fish-speech#793]
### Self Checks

- [X] This template is only for bug reports. For questions, please visit [Discussions](https://github.com/fishaudio/fish-speech/discussions).
- [X] I have thoroughly reviewed the project documentation (installation, training, inference) but couldn't find information to solve my problem. [English](https://speech.fish.audio/) [中文](https://speech.fish.audio/zh/) [日本語](https://speech.fish.audio/ja/) [Portuguese (Brazil)](https://speech.fish.audio/pt/)
- [X] I have searched for existing issues, including closed ones. [Search issues](https://github.com/fishaudio/fish-speech/issues)
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/fishaudio/fish-speech/issues/515)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template and fill in all required fields.

### Cloud or Self Hosted

Self Hosted (Source)

### Environment Details

windows 11,Python 3.10.11

### Steps to Reproduce

1. Run install_env.bat,everthing ok,install completed.
2. Run start.bat,showing Traceback ,but still auto open webui.

### ✔️ Expected Behavior

Program running normally.

### ❌ Actual Behavior

Active code page: 65001
"HF_ENDPOINT: https://hf-mirror.com"
"NO_PROXY: localhost, 127.0.0.1, 0.0.0.0"
gitattributes 不存在，从 Hugging Face 仓库下载...
L:\fish\fishenv\env\lib\site-packages\huggingface_hub\file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
L:\fish\fishenv\env\lib\site-packages\huggingface_hub\file_download.py:832: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
Traceback (most recent call last):
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\utils\_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hf-mirror.com/fishaudio/fish-speech-1.5/resolve/main/gitattributes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\fish\tools\download_models.py", line 52, in <module>
    check_and_download_files(repo_id_1, files_1, local_dir_1)
  File "L:\fish\tools\download_models.py", line 13, in check_and_download_files
    hf_hub_download(
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\file_download.py", line 840, in hf_hub_download
    return _hf_hub_download_to_local_dir(
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\file_download.py", line 1068, in _hf_hub_download_to_local_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\file_download.py", line 1374, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\file_download.py", line 1294, in get_hf_file_metadata
    r = _request_wrapper(
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\file_download.py", line 278, in _request_wrapper
    response = _request_wrapper(
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\file_download.py", line 302, in _request_wrapper
    hf_raise_for_status(response)
  File "L:\fish\fishenv\env\lib\site-packages\huggingface_hub\utils\_http.py", line 417, in hf_raise_for_status
    raise _format(EntryNotFoundError, message, response) from e
huggingface_hub.errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6771653c-4a0958865b6913331e73c623;601e1c8b-de50-4301-8bbf-57c0b8ddaeca)

Entry Not Found for url: https://hf-mirror.com/fishaudio/fish-speech-1.5/resolve/main/gitattributes.

Start HTTP API...
Debug: flags = --listen 0.0.0.0:8080 --llama-checkpoint-path "checkpoints/fish-speech-1.5" --decoder-checkpoint-path "checkpoints/fish-speech-1.5/firefly-gan-vq-fsq-8x1024-21hz-generator.pth" --decoder-config-name firefly_gan_vq

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "L:\fish\fishenv\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "L:\fish\fishenv\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "L:\fish\tools\api_server.py", line 22, in <module>
    from tools.server.api_utils import MsgPackRequest, parse_args
  File "L:\fish\tools\server\api_utils.py", line 9, in <module>
    from tools.inference_engine import TTSInferenceEngine
  File "L:\fish\tools\inference_engine\__init__.py", line 11, in <module>
    from fish_speech.utils import autocast_exclude_mps, set_seed
  File "L:\fish\fish_speech\utils\__init__.py", line 4, in <module>
    from .instantiators import instantiate_callbacks, instantiate_loggers
  File "L:\fish\fish_speech\utils\instantiators.py", line 5, in <module>
    from pytorch_lightning import Callback
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\utilities\types.py", line 36, in <module>
    from torchmetrics import Metric
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\__init__.py", line 37, in <module>
    from torchmetrics import functional  # noqa: E402
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 70, in <module>
    from torchmetrics.functional.audio.dnsmos import deep_noise_suppression_mean_opinion_score
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\audio\dnsmos.py", line 27, in <module>
    import onnxruntime as ort
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "L:\fish\fishenv\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "L:\fish\fishenv\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "L:\fish\tools\api_server.py", line 22, in <module>
    from tools.server.api_utils import MsgPackRequest, parse_args
  File "L:\fish\tools\server\api_utils.py", line 9, in <module>
    from tools.inference_engine import TTSInferenceEngine
  File "L:\fish\tools\inference_engine\__init__.py", line 11, in <module>
    from fish_speech.utils import autocast_exclude_mps, set_seed
  File "L:\fish\fish_speech\utils\__init__.py", line 4, in <module>
    from .instantiators import instantiate_callbacks, instantiate_loggers
  File "L:\fish\fish_speech\utils\instantiators.py", line 5, in <module>
    from pytorch_lightning import Callback
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\utilities\types.py", line 36, in <module>
    from torchmetrics import Metric
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\__init__.py", line 37, in <module>
    from torchmetrics import functional  # noqa: E402
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 70, in <module>
    from torchmetrics.functional.audio.dnsmos import deep_noise_suppression_mean_opinion_score
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\audio\dnsmos.py", line 27, in <module>
    import onnxruntime as ort
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError

Next launch the page...
['', 'L:\\fish\\fish_speech\\webui', 'L:\\fish', 'L:\\fish\\fishenv\\env\\python310.zip', 'L:\\fish\\fishenv\\env\\DLLs', 'L:\\fish\\fishenv\\env\\lib', 'L:\\fish\\fishenv\\env', 'C:\\Users\\Naught\\AppData\\Roaming\\Python\\Python310\\site-packages', 'C:\\Users\\Naught\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32', 'C:\\Users\\Naught\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32\\lib', 'C:\\Users\\Naught\\AppData\\Roaming\\Python\\Python310\\site-packages\\Pythonwin', 'L:\\fish\\fishenv\\env\\lib\\site-packages', '__editable__.fish_speech-0.1.0.finder.__path_hook__']
You are in  L:\fish
2024-12-29 23:05:42.755 | WARNING  | __main__:list_llama_models:598 - No LLaMA model found
2024-12-29 23:05:42.779 | WARNING  | __main__:list_decoder_models:588 - No decoder model found
2024-12-29 23:05:42.784 | WARNING  | __main__:list_llama_models:598 - No LLaMA model found
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by supertaog** [comment]
在huggingface仓库里将1.5或1.4模型的 gitattributes文件下载到本地对应的模型存放目录下就OK了

**Comment by NaughtDZ** [comment]
> 在huggingface仓库里将1.5或1.4模型的 gitattributes文件下载到本地对应的模型存放目录下就OK了

可以了，但是还有一个小报错
Active code page: 65001
"HF_ENDPOINT: https://hf-mirror.com"
"NO_PROXY: localhost, 127.0.0.1, 0.0.0.0"
gitattributes 已存在，跳过下载。
model.pth 已存在，跳过下载。
README.md 已存在，跳过下载。
special_tokens.json 已存在，跳过下载。
tokenizer.tiktoken 已存在，跳过下载。
config.json 已存在，跳过下载。
firefly-gan-vq-fsq-8x1024-21hz-generator.pth 已存在，跳过下载。
ffmpeg.exe 已存在，跳过下载。
ffprobe.exe 已存在，跳过下载。
asr-label-win-x64.exe 已存在，跳过下载。

Start HTTP API...
Debug: flags = --listen 0.0.0.0:8080 --llama-checkpoint-path "checkpoints/fish-speech-1.5" --decoder-checkpoint-path "checkpoints/fish-speech-1.5/firefly-gan-vq-fsq-8x1024-21hz-generator.pth" --decoder-config-name firefly_gan_vq

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "L:\fish\fishenv\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "L:\fish\fishenv\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "L:\fish\tools\api_server.py", line 22, in <module>
    from tools.server.api_utils import MsgPackRequest, parse_args
  File "L:\fish\tools\server\api_utils.py", line 9, in <module>
    from tools.inference_engine import TTSInferenceEngine
  File "L:\fish\tools\inference_engine\__init__.py", line 11, in <module>
    from fish_speech.utils import autocast_exclude_mps, set_seed
  File "L:\fish\fish_speech\utils\__init__.py", line 4, in <module>
    from .instantiators import instantiate_callbacks, instantiate_loggers
  File "L:\fish\fish_speech\utils\instantiators.py", line 5, in <module>
    from pytorch_lightning import Callback
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\utilities\types.py", line 36, in <module>
    from torchmetrics import Metric
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\__init__.py", line 37, in <module>
    from torchmetrics import functional  # noqa: E402
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 70, in <module>
    from torchmetrics.functional.audio.dnsmos import deep_noise_suppression_mean_opinion_score
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\audio\dnsmos.py", line 27, in <module>
    import onnxruntime as ort
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "L:\fish\fishenv\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "L:\fish\fishenv\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "L:\fish\tools\api_server.py", line 22, in <module>
    from tools.server.api_utils import MsgPackRequest, parse_args
  File "L:\fish\tools\server\api_utils.py", line 9, in <module>
    from tools.inference_engine import TTSInferenceEngine
  File "L:\fish\tools\inference_engine\__init__.py", line 11, in <module>
    from fish_speech.utils import autocast_exclude_mps, set_seed
  File "L:\fish\fish_speech\utils\__init__.py", line 4, in <module>
    from .instantiators import instantiate_callbacks, instantiate_loggers
  File "L:\fish\fish_speech\utils\instantiators.py", line 5, in <module>
    from pytorch_lightning import Callback
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "L:\fish\fishenv\env\lib\site-packages\pytorch_lightning\utilities\types.py", line 36, in <module>
    from torchmetrics import Metric
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\__init__.py", line 37, in <module>
    from torchmetrics import functional  # noqa: E402
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\audio\__init__.py", line 70, in <module>
    from torchmetrics.functional.audio.dnsmos import deep_noise_suppression_mean_opinion_score
  File "L:\fish\fishenv\env\lib\site-packages\torchmetrics\functional\audio\dnsmos.py", line 27, in <module>
    import onnxruntime as ort
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\Naught\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError

Next launch the page...
['', 'L:\\fish\\fish_speech\\webui', 'L:\\fish', 'L:\\fish\\fishenv\\env\\python310.zip', 'L:\\fish\\fishenv\\env\\DLLs', 'L:\\fish\\fishenv\\env\\lib', 'L:\\fish\\fishenv\\env', 'C:\\Users\\Naught\\AppData\\Roaming\\Python\\Python310\\site-packages', 'C:\\Users\\Naught\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32', 'C:\\Users\\Naught\\AppData\\Roaming\\Python\\Python310\\site-packages\\win32\\lib', 'C:\\Users\\Naught\\AppData\\Roaming\\Python\\Python310\\site-packages\\Pythonwin', 'L:\\fish\\fishenv\\env\\lib\\site-packages', '__editable__.fish_speech-0.1.0.finder.__path_hook__']
You are in  L:\fish
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by ctykwz** [comment]
gitattributes 默认路径是要放在哪里呢
