### ISSUE TITLE
[BUG] dockerfile

### ISSUE THREAD

**Issue by qiuyuzhao** [fishaudio/fish-speech#86]
通过dockerfile构建的docker， 在执行
python tools/vqgan/inference.py -i codes_0.npy --checkpoint-path checkpoints/vqgan-v1.pth 提示
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'fish_speech.models.vqgan' has no attribute 'spectrogram'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/exp/fish_speech/models/vqgan/spectrogram.py", line 2, in <module>
    import torchaudio.functional as F
ModuleNotFoundError: No module named 'torchaudio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'fish_speech.models.vqgan.spectrogram.LogMelSpectrogram':
ModuleNotFoundError("No module named 'torchaudio'")
Are you sure that 'spectrogram' is importable from module 'fish_speech.models.vqgan'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/exp/tools/vqgan/inference.py", line 147, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/exp/tools/vqgan/inference.py", line 41, in main
    model: LightningModule = instantiate(cfg.model)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'fish_speech.models.vqgan.spectrogram.LogMelSpectrogram', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.mel_transform
```

，通过命令
# 安装 pytorch nightly 版本
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

# 安装 flash-attn (适用于linux)
pip3 install ninja && MAX_JOBS=4 pip3 install flash-attn --no-build-isolation
安装后， 运行 python tools/llama/generate.py， 提示
```
Traceback (most recent call last):
  File "/exp/tools/llama/generate.py", line 28, in <module>
    from fish_speech.models.text2semantic.llama import Transformer
  File "/exp/fish_speech/models/text2semantic/__init__.py", line 1, in <module>
    from .lit_module import TextToSemantic
  File "/exp/fish_speech/models/text2semantic/lit_module.py", line 12, in <module>
    from fish_speech.models.text2semantic.llama import Transformer
  File "/exp/fish_speech/models/text2semantic/llama.py", line 12, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
```

**Comment by AnyaCoder** [comment]
安装torchaudio（就是这个命令pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121）后，先不要安装flash-attn, 看看能不能跑通。如果需要这边能出个教学安装flash-attn, 前提是确保你的显卡支持flash-attn。

**Comment by qiuyuzhao** [comment]
> pip3 install --pre torch torchvision torchaudio --index-url [https://download.pytorch.org/whl/nightly/cu121](https://download.pytorch.org/whl/nightly/cu121%EF%BC%89%E5%90%8E%EF%BC%8C%E5%85%88%E4%B8%8D%E8%A6%81%E5%AE%89%E8%A3%85flash-attn)
您好，不安装flash-attn可以跑通， 不按照对推理和训练有什么影响吗，我是3090的卡

**Comment by AnyaCoder** [comment]
安装flash-attn可以明显地提高训练和推理的速度，但需要满足一些条件。

1. CUDA版本(12.x)和安装的torch版本一致(12.1及以上)。
2. CUDA版本(12.2)和flash-attn包的CUDA版本一致，并且python版本一致(3.10)，torch版本一致(2.2), 选择ABI=FALSE的包

综合以上，flash_attn-2.5.2+cu122torch2.2cxx11abiFALSE-cp310-cp310-linux_x86_64.whl 就是一个符合条件的安装包体。加上你的显卡符合架构要求，故可以成功安装。

**Comment by leng-yue** [comment]
推理的话不太需要 flash attn, 可以先不装. 这个错应该是 flash attn 和 pytorch 版本不匹配导致的.

**Comment by leng-yue** [comment]
已在 dev 分支修复.
