### ISSUE TITLE
训练报错[BUG]

### ISSUE THREAD

**Issue by qiuyuzhao** [fishaudio/fish-speech#90]
您好， 在训练第二阶段的时候提示：
 python fish_speech/train.py --config-name text2semantic_finetune
[2024-02-19 11:59:57,926][__main__][INFO] - [rank: 0] Instantiating datamodule <fish_speech.datasets.text.TextDataModule>
[2024-02-19 11:59:58,658][datasets][INFO] - PyTorch version 2.3.0.dev20240218+cu121 available.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[2024-02-19 12:00:43,399][__main__][INFO] - [rank: 0] Instantiating model <fish_speech.models.text2semantic.TextToSemantic>
[2024-02-19 12:00:47,534][__main__][INFO] - [rank: 0] Instantiating callbacks...
[2024-02-19 12:00:47,534][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2024-02-19 12:00:47,539][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.ModelSummary>
[2024-02-19 12:00:47,540][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.LearningRateMonitor>
[2024-02-19 12:00:47,541][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating callback <fish_speech.callbacks.GradNormMonitor>
[2024-02-19 12:00:47,542][__main__][INFO] - [rank: 0] Instantiating loggers...
[2024-02-19 12:00:47,542][fish_speech.utils.instantiators][INFO] - [rank: 0] Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2024-02-19 12:00:47,553][__main__][INFO] - [rank: 0] Instantiating trainer <lightning.pytorch.trainer.Trainer>
Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.model_summary.ModelSummary'>]. Skipping setting a default `ModelSummary` callback.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-02-19 12:00:47,818][__main__][INFO] - [rank: 0] Logging hyperparameters!
[2024-02-19 12:00:47,992][__main__][INFO] - [rank: 0] Starting training!
[2024-02-19 12:00:47,994][__main__][INFO] - [rank: 0] Resuming from checkpoint: checkpoints/text2semantic-400m-v0.2-4k.pth
[2024-02-19 12:00:47,995][__main__][INFO] - [rank: 0] Resuming weights only!
[2024-02-19 12:00:48,694][__main__][INFO] - [rank: 0] Error loading state dict: <All keys matched successfully>
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[2024-02-19 12:00:55,462][datasets][INFO] - PyTorch version 2.3.0.dev20240218+cu121 available.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

  | Name             | Type        | Params
-------------------------------------------------
0 | model            | Transformer | 384 M 
1 | model.embeddings | Embedding   | 38.0 M
2 | model.layers     | ModuleList  | 308 M 
3 | model.norm       | RMSNorm     | 1.0 K 
4 | model.output     | Linear      | 38.0 M
-------------------------------------------------
384 M     Trainable params
0         Non-trainable params
384 M     Total params
1,537.085 Total estimated model params size (MB)
Sanity Checking: |                                                                                                                                                     | 0/? [00:00<?, ?it/s][2024-02-19 12:01:50,609][fish_speech.utils.utils][ERROR] - [rank: 0] 
Traceback (most recent call last):
  File "/exp/fish_speech/utils/utils.py", line 66, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/exp/fish_speech/train.py", line 94, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 1030, in _run_stage
    self._run_sanity_check()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 1059, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 700, in reraise
    exception = self.exc_type(msg)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 383, in __init__
    with state.condition:
AttributeError: 'str' object has no attribute 'condition'
请问这是什么原因？

**Comment by Stardust-minus** [comment]
没有启动data_server或者没有连接成功，检查一下

**Comment by qiuyuzhao** [comment]
> 没有启动data_server或者没有连接成功，检查一下

请问这个怎么算启动或者连接成功， 执行data_server/target/release/data_server \
    --files "data/quantized-dataset-ft.protos" 命令后很长时间没有反应，这一步正常要花费多久？

**Comment by leng-yue** [comment]
可以开启日志显示, 看下多久加载好了.

**Comment by qiuyuzhao** [comment]
> 可以开启日志显示, 看下多久加载好了.

请问这个日志怎么开启，好几个小时没有反应

**Comment by qiuyuzhao** [comment]
> 可以开启日志显示, 看下多久加载好了.

对不起是我的问题，我存的是.txt, 要到config里把.lab改成txt就可以了，谢谢
